### ISSUE TITLE
[FR] provide helm chart

### ISSUE THREAD

**Issue by Hokwang** [quay/clair#1105]
Hi,

I think v4 will come soon.

Please provide helm chart for install clair v4 on kubernetes.

Do you have a plan for this or consider other way (native yaml, operator, ...)?

**Comment by msrb** [comment]
Related issue: https://github.com/quay/clair/issues/928.

**Comment by ldelossa** [comment]
I doubt we will support helm. While not officially planed an Operator is very likely. We will also consider Kustomize after evaluation. 

Community can contribute helm into /contrib directory.

**Comment by abdennour** [comment]
@ldelossa  **Helm** is Top 1 as per [CNCF landscape in k8s package managers](https://landscape.cncf.io/).
![image](https://user-images.githubusercontent.com/1788384/103148069-e17c6c80-476c-11eb-94b8-56ffe5fdb1e0.png)

A cloud-native software which does not support Helm, it means one of two things: 
1. Software contributors do not know Helm.
2. Or establish a Vendor lock-in to another alternative technology.

If (1) is the problem, please accept contribution.
If (2) is the problem , we will not be able to argue more since CoreOs is acquired by your company.

**Comment by hdonnay** [comment]
As @ldelossa said,
> Community can contribute helm into /contrib directory.

There hasn't been such a contribution yet.

I don't appreciate the imputation that we maintainers are attempting something nefarious by not using the same software you do.
