### ISSUE TITLE
matcher/api/v1/vulnerability_report giving 404 Not found

### ISSUE THREAD

**Issue by kalrashubham49** [quay/clair#1151]
### Description of Problem / Feature Request

I am using clair release v4.0 for scanning images., Indexing has been done , but i am not able to get Vulnerability report from Clair when trying to use "http://clairaddr:6060/matcher/api/v1/vulnerability_report/mymanifesthash" endpoint i am getting 404 Page not found. 

I have checked , above given sha has been indexed and i am able to get the index report for sha i am using in vulnerability report.

Project discussion and other meta topics should be discussed on the mailing list.

### Expected Outcome

It needs to provide vulnerability report for indexed hash

### Actual Outcome

404 Not found

### Environment

- Clair version/image: v4.0
- Clair client name/version:  alpine
- Host OS:  Ubuntu
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Network/Firewall setup:

**Comment by ldelossa** [comment]
@kalrashubham49 can you provide both Indexer and Matcher logs, along with your config, when you experience this 404? 

Under first impression, without much info, its possible the Matcher cannot contact the Indexer. This could be because of bad configuration or some network partition between the two services.

**Comment by abcd-ABCD-1234** [comment]
Hi @ldelossa  @hdonnay 
I am looking for documents to run clair in the distributed mode...but unfortunately could not find anything related. Just a query, can't we simply run all 3 modes (indexer, matcher, and notifier) on 3 different ports, and then submit the manifest? It's because if we start clair in the indexer mode on a port, we won't be able to start clair in the other 2 modes on the same port. And if not, can you please point me/ guide me for some documentation for running clair in the distributed mode?

**Comment by hdonnay** [comment]
> I am looking for documents to run clair in the distributed mode...but unfortunately could not find anything related.

https://quay.github.io/clair/howto/deployment.html

> Just a query, can't we simply run all 3 modes (indexer, matcher, and notifier) on 3 different ports, and then submit the manifest? 

Sure, you'd just need to have 3 different configurations. The preferred way to do it would be to have the same configuration and container, and have an orchestration layer (k8s, a pile of shell scripts, etc) run them in different modes with appropriate networking and load balancing. It'd be much simpler to just use combo mode, though.

**Comment by hdonnay** [comment]
It's been 6 months with no response from OP, closing.

**Comment by abcd-ABCD-1234** [comment]
Thank you @hdonnay. I am really new to k8s stuff. Can you please guide me on what exactly I need to research for running three modes of clair with same configuration?  Is it pods, or are there much simpler ways to achieve the goal?
