### ISSUE TITLE
[Question] Support scanning UBI images in 2.1.X branch

### ISSUE THREAD

**Issue by pealtrufo** [quay/clair#1237]
I am using Harbor registry 1.10 integrated with Clair and I am trying to understand if scanning UBI images is supported. This Harbor version comes out of the box with Clair version 2.1.3, but I am wondering if installing 2.1.6 would provide this support.

### Environment

- Clair version/image: 2.1.X
- Clair client name/version: N/A
- Host OS: N/A
- Kernel (e.g. `uname -a`): N/A 
- Kubernetes version (use `kubectl version`): N/A
- Network/Firewall setup: N/A

**Comment by hdonnay** [comment]
V2 is unmaintained, but if the images are sufficiently simple, the scanning itself may work. If any RPM modules are being used, the results will almost certainly be incorrect because of v2's lack of support for RPM modules. I have no idea if there's any UBI-specific data in the sources that v2 pulls in by default.
