### ISSUE TITLE
Approach of obtaining a list of layers information for target docker images

### ISSUE THREAD

**Issue by westlifezs** [quay/clair#127]
Hello,

I've understood that clair will need to take layers information for each docker image for vulnerability assessment based on our previous discussion. I am having several questions regarding how the layer information has been gathered or should be gathered in order to invoke the clair API.

Our environment is under docker registry V1 API, therefore I guess I should obtain target images' layer info through "GET /v1/images/(image_id)/ancestry" based on registry v1 api documentation:  https://docs.docker.com/v1.6/reference/api/registry_api

Other sources also mentioned that I need to use "docker history IMAGE_ID" to retrieve layer information for that image. However, I cannot see most of their IDs as they are all shown as "missing"

I checked the code in main.go of "analyze-local-images" tool regarding its information collection mechanism for layers. It seems like the layer info is collected through "func historyFromManifest(path string) ([]string, error)" by checking against a file called "manifest.json". However, I am unable to find such a file in the file system where the images are stored. 

I also checked the running script after run "analyze-local-images IMAGE_ID". Even though the number of the layers are the same as I obtained through "GET /v1/images/(image_id)/ancestry" but their IDs are completely different. 

I am just wondering, if I want to integrate our docker registry with clair, then what is the most convenient/straightforward approach (API, CLI or client) to obtain layers' (of the target images) information that required by clair API call for vulnerability assessment? Also shall I just aggregate all of the layers of the target image vulnerability report into one as the report of the target image?

Thank you very much!

**Comment by jzelinskie** [comment]
Hi,

You appear to be confused between the `docker save` format (used by `analyze-local-images`) and the v1 registry format. When you export an image from a local docker instance, it saves the image as a tarball of layer tarballs along with a manifest file that contains all the metadata for the image. When fetching an image from a registry, the docker client requests a manifest and then individually fetches all the layer tarballs listed in that manifest.

The `analyze-local-image` tool is best for local testing and not production. The best way to integrate Clair with a container registry is to have the registry `POST` newly pushed images to Clair's `/v1/layers` endpoint (most implementations do this asynchronously) and also create a new registry endpoint where Clair can `POST` notifications when vulnerabilities have been updated.

Assuming you're using the open source v1 docker registry which only has a CLI interface, I'm not really sure how to best expose this information to the end-user. I'd recommend taking a look some of the registries that support Web UIs and Clair integration like Quay or Dockyard. Either of these options would also get you registry v2 support, too.

**Comment by westlifezs** [comment]
thanks for the clarification! 

some questions regarding your statement  " The best way to integrate Clair with a container registry is to have the registry POST newly pushed images to Clair's /v1/layers endpoint (most implementations do this asynchronously) and also create a new registry endpoint where Clair can POST notifications when vulnerabilities have been updated."

1.do you mean I need to decompose the images into layers and then post them to  Clair's /v1/layers endpoint? If so, could you please let me know the most convenient approach to obtain detailed layers info of the target image? As I mentioned in my original post, I could not find a straightforward approach to do so.
2. when you say "most implementations do this asynchronously", could you please elaborate with a tiny example?
3. when you say: "create a new registry endpoint where Clair can POST notifications when vulnerabilities have been updated", do you mean create RPC to receive newly detected vulnerabilities in existing images or to update the local vulnerability database? 

I would like to learn more about docker registry v2 for clair integration. However, our environment does have certain constraints that prevent us adopting docker registry v2 API as of now. Therefore I will have to stick to V1 for now. If you have any additional suggestions regarding how could we integrate clair into docker registry V1, please let me know. I highly appreciate your feedback.

Thank you very much,

**Comment by westlifezs** [comment]
it seems like manifest only belongs to docker registry V2 API based on https://docs.docker.com/v1.6/registry/spec/api/. does it mean clair will not support docker registry v1?
Also, it seems like "image id" under registry v2 is created based on sha2 hash but randomly created under v1. will this also affect clair's support on docker registry v1? thanks

**Comment by Quentin-M** [comment]
Hi,

> 1.do you mean I need to decompose the images into layers and then post them to Clair's /v1/layers endpoint? If so, could you please let me know the most convenient approach to obtain detailed layers info of the target image? As I mentioned in my original post, I could not find a straightforward approach to do so.

Docker images are composed of layers, as defined by the [v1 Image Format spec](https://github.com/docker/docker/blob/master/image/spec/v1.md). Yes, you do need to post them one by one to Clair via `/v1/layers`. Thanks to this, Clair can re-use previous analysis, in other words, Clair does not need to re-analyze any layer that it has analyzed in the past. 

Your container registry already has the images decomposed in layers. We can't tell you too much about how to get the image's ancestry as it all depends on your registry's API. As described in the spec linked above, each layer pushed to a v1 registry contains an archive and a JSON metadata file. This metadata file contains the layer ID, parent layer ID. Thus, the history tree can be built from them (this is registry's job to do so). The archive is expected by `/v1/layers`, as well as the layer ID and parent layer ID.

> 1. When you said "most implementations do this asynchronously", could you please elaborate with a tiny example?
1. A Docker client executes `docker push` to the container registry.
2. The container registry ingests and stores every layer and all other information (such as tag name, ...) according the registry API spec.
3. The registry returns to the client the success of the operation.
4. Later on, a registry worker discovers that new layers have been stored and should be analyzed by Clair. It then calls `/v1/layers` for each of them, in the right order according to their history.
5. Clair analyzes each of them and returns success.

This is async because images are pushed and confirmed as pushed because Clair analyzed them. It's also possible to do it sync, although if we don't believe it is good practice in terms of performance. This can be interesting if you want to offer the possibility to break a push if there're critical vulnerabilities for example.

> 1. when you say: "create a new registry endpoint where Clair can POST notifications when vulnerabilities have been updated", do you mean create RPC to receive newly detected vulnerabilities in existing images or to update the local vulnerability database?

Clair can send HTTP POST requests to a specified endpoint to notify about new/updated/removed vulnerabilities and the layers that are now vulnerable / aren't vulnerable anymore (depending on the case). This is optional of course but recommended. Please refer to the [notifier doc](https://github.com/coreos/clair/blob/master/notifier/README.md) to learn more.

> I would like to learn more about docker registry v2 for clair integration. However, our environment does have certain constraints that prevent us adopting docker registry v2 API as of now. Therefore I will have to stick to V1 for now. If you have any additional suggestions regarding how could we integrate clair into docker registry V1, please let me know. I highly appreciate your feedback.

Clair is registry agnostic, it doesn't care about whether Docker Registry v1 or v2 is being used. It just cares about receiving a tree of archives that it can process, through its API. In fact, Clair works with [rkt](https://github.com/coreos/rkt) and OpenVZ too. Furthermore, your registry should probably abstract v1 / v2 for you as, at the end of the day, it just stores a bunch of layers/blobs with their history/tags. This shouldn't matter at all.

> it seems like manifest only belongs to docker registry V2 API based on https://docs.docker.com/v1.6/registry/spec/api/. does it mean clair will not support docker registry v1?
> Also, it seems like "image id" under registry v2 is created based on sha2 hash but randomly created under v1. will this also affect clair's support on docker registry v1? thanks

As said above, the registry API doesn't matter. Clair only speaks its own API language. Regarding the ID, this is a good question. Every unique layer must have their own ID in Clair's perspective. This should probably be an internal container registry ID and not the docker ID - for security reasons and to avoid any potential collision.

**Comment by westlifezs** [comment]
thank you for your elaboration. very helpful information.
still have some other questions related to clair API regarding posting layers.

in clair API README example. It says I will need to provide name, path, parent name and format values. I can only obtain name and parent name based on docker registry v1. even in the doc you provided regarding docker image specs, I cannot find where the format and path information is recorded. Are these two fields (format and path) required for posting layers? if so, do you know where shall I obtain such information? Here is the  POST LAYER example mentioned in clair doc.

POST http://localhost:6060/v1/layers HTTP/1.1

{
  "Layer": {
    "Name": "523ef1d23f222195488575f52a39c729c76a8c5630c9a194139cb246fb212da6",
    "Path": "/mnt/layers/523ef1d23f222195488575f52a39c729c76a8c5630c9a194139cb246fb212da6/layer.tar",
    "ParentName": "140f9bdfeb9784cf8730e9dab5dd12fbd704151cf555ac8cae650451794e5ac2",
    "Format": "Docker"
  }
}

thanks.

**Comment by Quentin-M** [comment]
- `Format` is `ACI` or `Docker`. In your particular case, you systematically want to use `Docker`.
- `Path` is either a local path (unlikely because Clair and the registry storage shouldn't run on the same host in prod environment) or an HTTP URL where the layer archive can be found. Basically, your container registry has to expose it securely and let Clair download it somehow.

**Comment by westlifezs** [comment]
okay, thanks for sharing. I will try to figure out where to find the URL.
Another related question is, can I possibly list all of the existing layers vulnerability information stored within clair? it seems like I am not allowed to do so:

root@clair-3603:~# curl -v http://localhost:6060/v1/layers
- Hostname was NOT found in DNS cache
-   Trying 127.0.0.1...
- Connected to localhost (127.0.0.1) port 6060 (#0)
  > GET /v1/layers HTTP/1.1
  > User-Agent: curl/7.35.0
  > Host: localhost:6060
  > Accept: _/_
  >
  < HTTP/1.1 405 Method Not Allowed
  < Content-Type: text/plain; charset=utf-8
  < X-Content-Type-Options: nosniff
  < Date: Tue, 29 Mar 2016 21:36:31 GMT
  < Content-Length: 19
  <
  Method Not Allowed
- Connection #0 to host localhost left intact

also I tried to post a layer to clair but got a 307. could you please let me know how should I debug this issue?

root@clair-3603:~# curl -v -X POST -d @post_layer.txt http://localhost:6060/v1/layers/
- Hostname was NOT found in DNS cache
-   Trying 127.0.0.1...
- Connected to localhost (127.0.0.1) port 6060 (#0)
  > POST /v1/layers/ HTTP/1.1
  > User-Agent: curl/7.35.0
  > Host: localhost:6060
  > Accept: _/_
  > Content-Length: 304
  > Content-Type: application/x-www-form-urlencoded
  >
- upload completely sent off: 304 out of 304 bytes
  < HTTP/1.1 307 Temporary Redirect
  < Location: /layers
  < Date: Tue, 29 Mar 2016 21:38:20 GMT
  < Content-Length: 0
  < Content-Type: text/plain; charset=utf-8
  <
- Connection #0 to host localhost left intact

here is the content I tried to post:

root@clair-3603:~# cat post_layer.txt
{
  "Layer": {
    "Name": "86bcb57631bd122c32b8e277b64b45ac00382e78e0d21530a50c090fd739d0ee",
    "Path": "/mnt/layers/86bcb57631bd122c32b8e277b64b45ac00382e78e0d21530a50c090fd739d0ee/layer.tar",
    "ParentName": "2bf4902415e362b7e531ac48c5bb4b265292375ae9b9bf735360be9cbca5f8e5",
    "Format": "Docker"
  }
}

thanks

**Comment by westlifezs** [comment]
could you please give me an example of a remote docker image layer URL? I searched through but I really could not find anything related to this use case. Looks like the mechanism (way of obtaining/downloading layers) is similar to "docker pull". However, even docker pull does not know each layer's specific location/path (it identifies layer through digest, right?). I am really curious regarding what content should I put for the layer path. also do you think the previous error (307) in my post related to the path I provided is incorrect? thanks

**Comment by westlifezs** [comment]
when you're talking about "an HTTP URL where the layer archive can be found", did you mean I just need to provide an URL which I can download the tar file (layer) through curl or wget?

**Comment by westlifezs** [comment]
In general I like clair a lot. But I think it will be nice if there are concrete examples illustrating how clair can be integrated with docker registries. For example, if there is a public layer in docker hub that can be used to show the effectiveness of clair, then it will be extremely helpful for users like me to understand how it works. also it will save lots of time for developers to answer questions. I am still trying to understand what I need to post "path" info to clair. is there a way to obtain such info through API? I searched through docker registry v1 api but could not find related information. any suggestions will be appreciated. thanks

**Comment by westlifezs** [comment]
I believe that found out a way of obtaining layer binary stream through docker registry v1 api. But I am still having error code when posting its path information to clair. I created another issue (#128) and am closing this one as they are already not the same topic.

**Comment by Quentin-M** [comment]
Hi,

Your 307 status code happens because you're calling `/v1/layers/` instead of `/v1/layers`. Clair simply corrects you automatically. Your call looks fine to me otherwise!

> when you're talking about "an HTTP URL where the layer archive can be found", did you mean I just need to provide an URL which I can download the tar file (layer) through curl or wget?

Exactly. That's what Clair does. It simply downloads the layer archive from the specified HTTP URL, just like wget or curl would do.
