### ISSUE TITLE
Clair does not detect Debian vulnerability

### ISSUE THREAD

**Issue by iainduncani** [quay/clair#1270]
### Description of Problem

I have an image that I know contains a version of `openssh-client` that is vulnerable to [CVE-2019-6111](https://security-tracker.debian.org/tracker/CVE-2019-6111) but when I scan it in Clair it does not detect this vulnerability.  Having dug into the problem I think there are two issues, firstly the packages in any layers other than the base are not detected, secondly when a package is a binary package it is not matched to its source.  More details on both of these below.

### Problem description
I have the following dockerfile that installs a vulnerable version of `openssh-client`:

```Dockerfile
FROM debian:stretch-slim

RUN echo 'deb http://snapshot.debian.org/archive/debian/20170625T040030Z stretch-proposed-updates main' >> /etc/apt/sources.list && \
  apt-get -o Acquire::Check-Valid-Until=false update && \
  apt-get install openssh-client=1:7.4p1-10+deb9u1 -y
```

### Expected Outcome

I expect to see the `openssh-client` listed in the list of installed packages and it to be vulnerable.

### Actual Outcome

`openssh-client` does not appear in the list of installed packages.  I looked at what is in the database and see that the layer does exist for the manifest as:

```SQL
SELECT COUNT(DISTINCT layer_id) FROM manifest_layer ml
INNER JOIN manifest m
ON m.id=ml.manifest_id
WHERE m.hash='<HASH>'
```

Returns `2` layers as expected, however, no packages are loaded from the second layer (that contains the `openssh-client` as the following only returns `1`:

```SQL
SELECT COUNT(DISTINCT psa.layer_id) FROM package p
INNER JOIN package_scanartifact psa
ON psa.package_id=p.id
INNER JOIN manifest_layer ml
ON ml.layer_id=psa.layer_id
INNER JOIN manifest m
ON m.id=ml.manifest_id
WHERE m.hash='<HASH>'
```

When looking at the logs I see a debug message come out saying:

```
didn't find an os-release or lsb release file
```

So I wonder if it is not scanning the extra layer because it does not have the base OS files, although I have not taken this investigation further.

### Problem description
To continue my investigation I then squashed the image into a single layer with this Dockerfile:

```Dockerfile
FROM debian:stretch-slim as base

RUN echo 'deb http://snapshot.debian.org/archive/debian/20170625T040030Z stretch-proposed-updates main' >> /etc/apt/sources.list && \
  apt-get -o Acquire::Check-Valid-Until=false update && \
  apt-get install openssh-client=1:7.4p1-10+deb9u1 -y

FROM scratch
COPY --from=base / /
```

### Expected Outcome

I expect to see the `openssh-client` listed in the list of installed packages and it to be vulnerable.

### Actual Outcome

`openssh-client` now appeared in the list of installed packages but it was not vulnerable.  The vulnerability report now contains the fact that the package is installed:

```JSON
"172": {
  "id": "172",
  "name": "openssh-client",
  "version": "1:7.4p1-10+deb9u1",
  "kind": "binary",
  "source": {
    "id": "171",
    "name": "openssh",
    "version": "1:7.4p1-10+deb9u1",
    "kind": "source",
    "normalized_version": "",
    "cpe": ""
  },
  "normalized_version": "",
  "arch": "amd64",
  "cpe": ""
}
```

Again I went to the database to try to figure out why this might not be vulnerable and see that the database only contains data about the binary vulnerabilities:

```SQL
SELECT COUNT(id) FROM vuln
WHERE dist_id = 'debian' AND package_kind <> 'binary'
```

Returns `0`.  Looking at what it has loaded for `CVE-2019-6111` I ran:

```SQL
SELECT * FROM vuln
WHERE dist_id = 'debian' AND name = 'CVE-2019-6111'
```

Which returns two results, both with a `package_name` of `openssh`, i.e. the source package but the `package_kind` is `binary` in both cases.  As I only have the `openssh_client` package installed and not the `openssh` package I think this is why it is not matching.

### Environment

- Clair version/image: I ran:
```Shell
$ git checkout v4.0.5
$ make local-dev-up-with-quay
```
- Clair client name/version: I accessed the API via curl
- Host OS: macos using docker
- Kernel (e.g. `uname -a`): Darwin Kernel Version 20.4.0
- Kubernetes version (use `kubectl version`): n/a
- Network/Firewall setup: All on localhost

**Comment by iainduncani** [comment]
I think the second problem I outlined above is a duplicate of #1125. The first problem seems to affect all images, not just Debian images.

**Comment by neijurli** [comment]
### Description of Problem ###

I tried recreating Problem 1 of the issue by creating and scanning images that add vulnerable packages with Clair V4 and it seems like the problem is still present.

### Test 1: Adding a vulnerable version of curl to debian:10 ###

There exists a vulnerability CVE-2021-22924 (https://security-tracker.debian.org/tracker/CVE-2021-22924) for curl:7.64.0-4+deb10u2 for debian buster. I have the following dockerfile that installs the package:
```Dockerfile
FROM debian:10
RUN echo 'deb http://deb.debian.org/debian buster main\ndeb-src http://deb.debian.org/debian buster main' >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install curl=7.64.0-4+deb10u2 -y
```
I have also confirmed that both layers are present in the manifest after scanning
```sql
SELECT COUNT(DISTINCT layer_id) FROM manifest_layer ml
INNER JOIN manifest m
ON m.id=ml.manifest_id
WHERE m.hash='<HASH>';
 count 
-------
     2
(1 row)
```

#### Expected Outcome ####
I expected to see curl listed in the list of packages as well as CVE-2021-22924 (https://security-tracker.debian.org/tracker/CVE-2021-22924) be listed in the vulnerabilities returned by GetVulnerabilityReport

#### Actual Outcome ####
curl did not appear in the list of packages, neither did the CVE.
I have tested and confirmed the CVE is reported for Clair V2.

### Test 2: Adding a vulnerable package to ubuntu:18.04 ###

There exists a vulnerability CVE-2021-38185 (https://ubuntu.com/security/CVE-2021-38185) for cpio versions through 2.13 for ubuntu 18.04. I have the following dockerfile that installs the package:

```Dockerfile
FROM ubuntu:18.04
RUN apt-get update && \
    apt-get install cpio=2.12+dfsg-6 -y
```

I have also confirmed that both layers are present in the manifest after scanning

```sql
SELECT COUNT(DISTINCT layer_id) FROM manifest_layer ml
INNER JOIN manifest m
ON m.id=ml.manifest_id
WHERE m.hash='<HASH>';
 count 
-------
     2
(1 row)
```

#### Expected Outcome ####
I expected to see cpio listed in the list of packages as well as CVE-2021-38185 (https://ubuntu.com/security/CVE-2021-38185) be listed in the vulnerabilities returned by GetVulnerabilityReport

#### Actual Outcome ####
cpio did not appear in the list of packages, neither did the CVE.
I have tested and confirmed the CVE is reported for Clair V2.

### Environment ###

* Clair version/image: Clair 4.2.0
* Clair client name/version: Access API via curl
* Host OS: AmazonLinux2 using docker
* Kernel (e.g. uname -a):
* Kubernetes version (use kubectl version): n/a
* Network/Firewall setup: localhost

**Comment by apurvmahajan** [comment]
@iainduncani Its been a while since you have opened this issue. Have you had any success with scanning images and working around these or do these issues still persist?

**Comment by apurvmahajan** [comment]
Hello @hdonnay. 

This appears to be a major gap in Clair v4 and a regression from Clair V2. It seems that Clair V4 is not suitable for scanning multi layer images. I did not see this issue while scanning images in the Quay registry and I am trying to figure out what we are doing wrong. Appreciate any inputs to help us understand the issue.

**Comment by iainduncani** [comment]
> @iainduncani Its been a while since you have opened this issue. Have you had any success with scanning images and working around these or do these issues still persist?

@apurvmahajan no, I haven't had a chance to look at the root cause of this yet or find a work around.

**Comment by SofyaTavrovskaya** [comment]
By default for debian and  ubuntu vulnerabilities "package_kind" field is specifying like BINARY: 
https://github.com/quay/claircore/blob/v0.5.4/pkg/ovalutil/dpkg.go#L130

When matсher creates requests to clair-db, he tries to find vulnerabilities in vuln TABLE by 5 fields:
"package_name",
"package_kind",
"dist_name",
"dist_id",
"dist_version". 

So, for example, for package shadow Clair v4 never finds vulnerabilities, because in index report shadow package is specifying like "source":
```
"168": {
      "id": "168",
      "name": "passwd",
      "version": "1:4.5-1.1",
      "kind": "binary",
      "source": {
        "id": "157",
        "name": "shadow",
        "version": "1:4.5-1.1",
        "kind": "source"
      },
      "arch": "amd64"
    },
```
And query to clair-db always returns 0, if package_kind = 'source'.
https://github.com/quay/claircore/blob/v0.5.4/internal/vulnstore/postgres/querybuilder.go#L97.

But vulnerabilities for shadow package are presented in Clair-db and in Oval DB.

Maybe, it's not correct to specify by default for all ubuntu and debian vulnerabilities package_kind like BINARY, because we can't get info about package kind (source or binary) from open DB: https://www.debian.org/security/oval/oval-definitions-buster.xml. 

And It's not related only to Debian-based images, Ubuntu images are affected too.

**Comment by crozzy** [comment]
Hi guys, 

Relating to your first point @iainduncani, the FS that is contained in the second layer:

```
RUN echo 'deb http://snapshot.debian.org/archive/debian/20170625T040030Z stretch-proposed-updates main' >> /etc/apt/sources.list && \
  apt-get -o Acquire::Check-Valid-Until=false update && \
  apt-get install openssh-client=1:7.4p1-10+deb9u1 -y
```
contains these files at the `/var/lib/dpkg` dir:
![image](https://user-images.githubusercontent.com/1027041/131028975-89cd51f2-f54c-46f7-8b93-bbb53e353432.png)

The dpkg scanner will check for the `status` and `available` files in order to identify the dpkg DB dir and hence will skip this dir: https://github.com/quay/claircore/blob/main/dpkg/scanner.go#L101.

This probably merits a change that updates the identification method for the dpkg DB dir.

**Comment by crozzy** [comment]
https://github.com/quay/claircore/pull/209 see this PR for the introduction of the `package_kind` query parameter, relating to surfacing duplicate vulnerabilities when the `source` and the `binary` packages have the same name.

**Comment by apurvmahajan** [comment]
@SofyaTavrovskaya thanks for the pointers! @crozzy thanks for the looking into this and for the PR for the first problem. 

For the second problem, with the introduction of `package_kind`, we actually have a regression for the image scans results.  
Would it be better to query for binary package_kind as @SofyaTavrovskaya mentions? It may better to show duplicate results for now instead of not showing any results at all even though vulnerabilities are present in the image. Anyone using Clair V4 for scanning will not see the vulnerabilities at all.

Meanwhile, is there an alternate source with the `package_kind` information that we can use to supplement the vulnerability data and correctly identify the `package_kind`.

**Comment by apurvmahajan** [comment]
I have been looking into some of the data coming in from the OVAL feed. I was testing with an updated query ([here](https://github.com/quay/claircore/blob/v0.5.4/internal/vulnstore/postgres/querybuilder.go#L36)) which does not match the package_kind for source packages. Seems like the Debian OVAL feed either has incorrect data or incomplete data.

Specifically I checked for 2 CVEs. For the `openssl` CVE's [CVE-2016-6309](https://security-tracker.debian.org/tracker/CVE-2016-6309) and [CVE-2010-4252](https://security-tracker.debian.org/tracker/CVE-2010-4252) that are both fixed for debian buster but were reported in the results. The vuln table has both entries with the `fixed_in_version` as `0:0` and results in the vulnerability being reported because it matches [here](https://github.com/quay/claircore/blob/main/debian/matcher.go#L58-L60). 

```
clair=# select name, package_name, fixed_in_version from vuln where updater = 'debian-buster-updater' and name = 'CVE-2016-6309' LIMIT 1;
-[ RECORD 1 ]----+--------------
name             | CVE-2016-6309
package_name     | openssl
fixed_in_version | 0:0
```

OVAL data feed entry for CVE-2016-6309
```
    <definition class="vulnerability" id="oval:org.debian:def:20166309" version="1">
      <metadata>
        <title>CVE-2016-6309</title>
        <affected family="unix">
          <platform>Debian GNU/Linux 10</platform>
          <product>openssl</product>
        </affected>
        <reference ref_id="CVE-2016-6309" ref_url="https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-6309" source="CVE"/>
        <description>statem/statem.c in OpenSSL 1.1.0a does not consider memory-block movement after a realloc call, which allows remote attackers to cause a denial of service (use-after-free) or possibly execute arbitrary code via a crafted TLS session.</description>
        <debian>
          <date>2021-08-25</date>
          <moreinfo></moreinfo>
        </debian>
      </metadata>
      <criteria comment="Release section" operator="AND">
        <criterion comment="Debian 10 is installed" test_ref="oval:org.debian.oval:tst:1"/>
        <criteria comment="Architecture section" operator="OR">
          <criteria comment="Architecture independent section" operator="AND">
            <criterion comment="all architecture" test_ref="oval:org.debian.oval:tst:2"/>
            <criterion comment="openssl DPKG is earlier than 0" test_ref="oval:org.debian.oval:tst:11104"/>
          </criteria>
        </criteria>
      </criteria>
    </definition>

```

I checked the Debian [json](https://security-tracker.debian.org/tracker/data/json) feed as well and it has an additional `status` in the feed which shows the two vulnerabilities above as `resolved`. The `fixed_version` is 0 in the json feed as well.

It seems like either the `fixed_in_version` information is incorrect for these vulnerabilities (in both feeds) or we need the additional `status` column in the OVAL feed to determine if the vulnerability is still open or has been resolved.

**Debian image**

I was testing with the same Debian image as @neijurli used above:

```Dockerfile
FROM debian:10
RUN echo 'deb http://deb.debian.org/debian buster main\ndeb-src http://deb.debian.org/debian buster main' >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get install curl=7.64.0-4+deb10u2 -y
```

**Comment by apurvmahajan** [comment]
@hdonnay @crozzy 

I did a similar exercise as above for the ubuntu based feed to check if there are any false positives being reported. I tested Clair V4 scanning with an updated query ([here](https://github.com/quay/claircore/blob/v0.5.4/internal/vulnstore/postgres/querybuilder.go#L36)) which does not match the package_kind for source packages. 

Comparing these results to Clair V2, I saw 21 more vulnerabilities being reported - all reported as `Low` severity. These seem fine except 1 which is has `Rejected` status was also reported with `Low` severity.

Needs Triage
[CVE-2017-18018](https://ubuntu.com/security/CVE-2017-18018)
[CVE-2018-12886](https://ubuntu.com/security/CVE-2018-12886)
[CVE-2018-19211](https://ubuntu.com/security/CVE-2018-19211)
[CVE-2019-15847](https://ubuntu.com/security/CVE-2019-15847)
[CVE-2021-20193](https://ubuntu.com/security/CVE-2021-20193)
[CVE-2021-33574](https://ubuntu.com/security/CVE-2021-33574)
[CVE-2021-35942](https://ubuntu.com/security/CVE-2021-35942)
[CVE-2021-36084](https://ubuntu.com/security/CVE-2021-36084)
[CVE-2021-36085](https://ubuntu.com/security/CVE-2021-36085)
[CVE-2021-36086](https://ubuntu.com/security/CVE-2021-36086)
[CVE-2021-36087](https://ubuntu.com/security/CVE-2021-36087)
[CVE-2021-37600](https://ubuntu.com/security/CVE-2021-37600)
[CVE-2021-38604](https://ubuntu.com/security/CVE-2021-38604)

Ignored
[CVE-2018-20796](https://ubuntu.com/security/CVE-2018-20796)
[CVE-2019-1010022](https://ubuntu.com/security/CVE-2019-1010022)
[CVE-2019-1010023](https://ubuntu.com/security/CVE-2019-1010023)
[CVE-2019-1010024](https://ubuntu.com/security/CVE-2019-1010024)
[CVE-2019-6488](https://ubuntu.com/security/CVE-2019-6488)
[CVE-2019-7309](https://ubuntu.com/security/CVE-2019-7309)
[CVE-2020-13776](https://ubuntu.com/security/CVE-2020-13776)

Rejected
[CVE-2019-9619](https://ubuntu.com/security/CVE-2019-9619)

In the database all these vulnerabilities have an empty value for the fixed in version and match [here](https://github.com/quay/claircore/blob/main/ubuntu/matcher.go#L49-L52).

**Ubuntu Image**

```
FROM ubuntu:18.04
RUN apt-get update && \
    apt-get install cpio=2.12+dfsg-6 -y
```

**Comment by SofyaTavrovskaya** [comment]
@apurvmahajan Debian OVAL database seems to have a lot of problems. It is generated by code that hasn't been updated a very long period of time, it still uses python2.7 (https://salsa.debian.org/webmaster-team/webwml/-/blob/master/english/security/oval/generate.py) . I found this conversation about issue in `fixed_version: 0:0`, but haven't found any PRs that resolve this problem: https://groups.google.com/g/linux.debian.security/c/zYqDWOAT8xQ. 
During investigation I found several bugs in script that generate OVAL.xml and created PR (https://salsa.debian.org/webmaster-team/webwml/-/merge_requests/737) , but for today I haven't had any reviews or merge . Maybe, they don't support this script at all. 

And I found issues in other projects that are used debian OVAL DB, for example, this one: https://github.com/wazuh/wazuh/issues/5271, where we can see such problem: "Apart from the packages that the OVAL marks as vulnerable for each CVE, there exist some cases where more than one package is affected and we are missing them because the OVAL doesn't provide the whole list of affected packages."

**Comment by apurvmahajan** [comment]
@SofyaTavrovskaya Thanks for the investigation and the merge request you have created! 

The CVE issue that I had found seemed to be due to data quality issues with the Debian JSON feed itself where it does not have the correct version information for the CVE and defaults to the value 0. Your merge request points to a different issue where the parsing of the JSON -> OVAL feed is incorrect and the version information is not parsed. Is my understanding correct? Trying to understand if this is enough to resolve the OVAL version issues or the data quality issues are separate. 

The other issue you have mentioned regarding OVAL not reporting all packages is also concerning. I have been connecting with the Clair team on the IRC channel and we are trying to figure out the way forward for the feed issues.

**Comment by SofyaTavrovskaya** [comment]
@apurvmahajan Nope, it doesn't resolve the whole issue with `fixed_version: 0:0`, OVAL database gets data from 2 sources:
1) from data. json file: https://security-tracker.debian.org/tracker/data/json 
2) by parsing wml files with info about vulnerabilities in this directory: https://salsa.debian.org/webmaster-team/webwml/-/tree/master/english/security.

My PR only fixes problem with incorrect parsing wml files, but it's not related to incorrect data in data.json. As you mentioned before CVE-2016-6309 in data.json has `fixed_version` is 0 and script gets this fixed_version: https://salsa.debian.org/webmaster-team/webwml/-/blob/master/english/security/oval/generate.py#L135

**Comment by iainduncani** [comment]
> This probably merits a change that updates the identification method for the dpkg DB dir.

Hi @crozzy I just saw that you did https://github.com/quay/claircore/pull/456 to fix this.  Thanks a lot!

One follow up question - I noted that it was in `main` but not `release-0.5` and that @hdonnay commented that it would require a version bump to be integrated.  Do either of you have a timelime as to when release 0.6 is going to come out for us to consume?

Thanks again for your work on this :-)

**Comment by crozzy** [comment]
Hi @iainduncani, can you consume the latest Clair version [v4.3.0](https://github.com/quay/clair/releases/tag/v4.3.0)? That includes claircore version v1.1.0 which includes quay/claircore#456.

**Comment by iainduncani** [comment]
@crozzy yes I can! I'd been looking at the releases in claircore which listed 0.5.5 as the last release and didn't see there was a v1.1.0 tag in there that was being used by Clair v4.3.0, will get onto to migrating to that today.  Thanks!

Is there an easy way to see breaking changes (we're going from v4.1.0), after digging in the changelog I saw for instance the [code comment on this migration](https://github.com/quay/claircore/blob/691f2023a1720a0579e688b69a2f4bfe1f4b7821/libindex/migrations/migration3.go#L8-L9) around needing to re-index after the migration completed but it would be good to know a complete list of this kind of thing...

**Comment by cathyyoung** [comment]
I've been looking into the `fixed_version: 0:0` provided by the Debian OVAL XML feed, which [as noted above](https://github.com/quay/clair/issues/1270#issuecomment-942248301) originates from Debian's source data.json having the `"fixed_version": "0"`. I believe this is not an error in the data, but a way to indicate that the CVE in question does not apply to this Debian version and therefore the package is not vulnerable.

I investigated 20-30 arbitrary CVEs that are listed in the source JSON as `"fixed_version": "0"` and found in every case it is a CVE that the Debian release is not affected by - e.g.

- [CVE-2021-26925](https://security-tracker.debian.org/tracker/CVE-2021-26925) - `[buster] - roundcube <not-affected> (Vulnerable code introduced later)`
- [CVE-2021-26713](https://security-tracker.debian.org/tracker/CVE-2021-26713) - `asterisk <not-affected> (Only affects 16.16.0 onwards)`
- [CVE-2020-6546](https://security-tracker.debian.org/tracker/CVE-2020-6546) - `chromium <not-affected> (debian package disables the installer)`
- [CVE-2020-6624](https://security-tracker.debian.org/tracker/CVE-2020-6624) - `Crash in CLI tool, no security impact`
- [CVE-2010-2266](https://security-tracker.debian.org/tracker/CVE-2010-2266) - `nginx <not-affected> (Confirmed Windows only, see bug #590768)`
- [CVE-2019-9923](https://security-tracker.debian.org/tracker/CVE-2019-9923) - `Crash in CLI tool, no security impact`

For the 2 CVEs that @apurvmahajan [investigated](https://github.com/quay/clair/issues/1270#issuecomment-917117459): 

> `openssl` CVE's [CVE-2016-6309](https://security-tracker.debian.org/tracker/CVE-2016-6309) and [CVE-2010-4252](https://security-tracker.debian.org/tracker/CVE-2010-4252) that are both fixed for debian buster but were reported in the results.

For both of these, the "Notes" field in the Debian tracker shows `openssl <not-affected>` for various reasons. So it appears that any CVE with `"fixed_version": "0"` is because Debian has reviewed and assessed the CVE as not applicable to their release, and hence there is no vulnerability present.

It should be safe for Clair to ignore these CVEs and remove them from the vulnerability report.

**Comment by SofyaTavrovskaya** [comment]
@cathyyoung Yes, you are right. 
If CVE  has  `<not-affected>` mark , the script marks the fixed version as '0' by default. It can be found in Debian's code that generates data.json https://salsa.debian.org/security-tracker-team/security-tracker/-/blob/master/lib/python/bugs.py#L575

**Comment by nmeyerhans** [comment]
@SofyaTavrovskaya's [merge request](https://salsa.debian.org/webmaster-team/webwml/-/merge_requests/737), as well as [a change that I proposed](https://salsa.debian.org/webmaster-team/webwml/-/merge_requests/752), have been merged by Debian. These should help improve the accuracy of the data in the OVAL feeds.

**Comment by iainduncani** [comment]
I've just come back to this issues as we've been seeing it in a few more of our test images.  Looking at the [Debian security FAQs](https://www.debian.org/security/faq) they say:

```
The announcement mail mentions the source package in which the vulnerability was present. Therefore, you should update all the binary packages from that source package.
```

I realise this is talking about the mailing list in particular but I would image it holds true for any security feed from Debian that they apply to the source package and not the binary package and therefore as @SofyaTavrovskaya [points out](https://github.com/quay/clair/issues/1270#issuecomment-905608336) the decision to set all Debian vulnerabilites as applying to binaries is wrong and Clair will only identify the occasions when the source name a vulnerability is reported against happens to match the binary name that is installed.

Given that I think this should change to `SOURCE` for Debian what I am not sure about is the consequences for Ubuntu which uses the same default.  I haven't managed to find an equivalent to the Debian FAQ that makes it clear source should be used although I do see that both @SofyaTavrovskaya and @apurvmahajan have seen similar problems on Ubuntu I'm not sure if we can make the assertion that all vulnerabilities should be reported against the source on Ubuntu.

One further problem is that in the Clair report that is produced it appears that when the source package matches the binary package Clair does not record the source information so for example in an image that has the `gnupg` and `gpvg` packages which are both provided by the `gnupg` source package the Clair report contains:

```
  "packages": {
    "1554971": {
      "id": "1554971",
      "name": "gnupg",
      "version": "1.4.18-7",
      "kind": "binary",
      "source": {
        "id": "161",
        "name": "",
        "version": ""
      },
      "arch": "amd64"
    },
    "1554963": {
      "id": "1554963",
      "name": "gpgv",
      "version": "1.4.18-7",
      "kind": "binary",
      "source": {
        "id": "1554962",
        "name": "gnupg",
        "version": "1.4.18-7",
        "kind": "source"
      },
      "arch": "amd64"
    },
  }
```

And it appears to omit the source package whenever it matches the binary name so therefore would not match if the vulnerability was only recorded for the source package.

**Comment by crozzy** [comment]
We recently merged this: https://github.com/quay/claircore/pull/550 into claircore. It builds the source->binary relationship when saving vulnerabilities and expands them so Debian vulnerabilities are now saved in the DB at binary level with their binary package names.

**Comment by iainduncani** [comment]
@crozzy this is great news!  I can confirm that this does indeed work for _most_ of our test images.  Sadly, the image reported in this issue still has a problem.  I can see that we are now getting a `vuln` entry for `DSA 4387-1` as expected but the fixed in version is wrong.  

The fixed in version in the `vuln` table is set to `0:1:7.4p1-10+deb9u5`, i.e. it has added an extra epoch of `0:` on the front so when the Debian matcher comes to [compare the two versions](https://github.com/quay/claircore/blob/main/debian/matcher.go#L62-L64) it thinks the installed version of `1:7.4p1-10+deb9u1` is higher than the fixed in version because it has an epoch of `1` compared to `0` for the fixed in version.

I see that this is loaded from the [oval XML file](https://github.com/quay/claircore/blob/main/pkg/ovalutil/dpkg.go). This is the definition in the oval XML:

```
    <definition class="patch" id="oval:org.debian:def:211953691737107272697670076309425281098" version="1">
      <metadata>
        <title>DSA-4387-1 openssh</title>
        <affected family="unix">
          <platform>Debian GNU/Linux 9</platform>
          <product>openssh</product>
        </affected>
        <reference ref_id="CVE-2018-20685" ref_url="https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-20685" source="CVE"/>
        <reference ref_id="CVE-2019-6109" ref_url="https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-6109" source="CVE"/>
        <reference ref_id="CVE-2019-6111" ref_url="https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-6111" source="CVE"/>
        <description>security update</description>
        <debian>
          <dsa>DSA-4387</dsa>
          <date>2019-02-09</date>
          <moreinfo>
Harry Sintonen from F-Secure Corporation discovered multiple vulnerabilities in OpenSSH, an implementation of the SSH protocol suite. All the vulnerabilities are in found in the scp client implementing the SCP protocol.</moreinfo>
        </debian>
      </metadata>
      <criteria comment="Release section" operator="AND">
        <criterion comment="Debian 9 is installed" test_ref="oval:org.debian.oval:tst:1"/>
        <criteria comment="Architecture section" operator="OR">
          <criteria comment="Architecture independent section" operator="AND">
            <criterion comment="all architecture" test_ref="oval:org.debian.oval:tst:2"/>
            <criterion comment="openssh DPKG is earlier than 1:7.4p1-10+deb9u5" test_ref="oval:org.debian.oval:tst:25340"/>
          </criteria>
        </criteria>
      </criteria>
    </definition>
    <dpkginfo_test check="all" check_existence="at_least_one_exists" comment="openssh is earlier than 1:7.4p1-10+deb9u5" id="oval:org.debian.oval:tst:25340" version="1" xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#linux">
      <object object_ref="oval:org.debian.oval:obj:6"/>
      <state state_ref="oval:org.debian.oval:ste:15793"/>
    </dpkginfo_test>
    <dpkginfo_state id="oval:org.debian.oval:ste:15793" version="1" xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#linux">
      <evr datatype="debian_evr_string" operation="less than">0:1:7.4p1-10+deb9u5</evr>
    </dpkginfo_state>
```

So when we get to the `evr` defined in the XML [to set the FixedInVersion](https://github.com/quay/claircore/blob/main/pkg/ovalutil/dpkg.go#L108) it says the test is to be less than `0:1:7.4p1-10+deb9u5` which does not correspond to the (correct) text in the criterion of `openssh DPKG is earlier than 1:7.4p1-10+deb9u5`.

I realise this is a fault in the Debian XML, should Clair handle such a mistake or do we need to go back to Debian and get the Oval feed updated?

**Comment by cathyyoung** [comment]
It appears that this bug in the Debian Oval feed output is likely due to [this section in the generation script](https://salsa.debian.org/webmaster-team/webwml/-/blob/36ad46455534cedf0fa7200df329508e31a99feb/english/security/oval/oval/definition/generator.py#L167):


```
    state = __createXMLElement("dpkginfo_state", 
      attrs={"id":stateId, 
        "version":"1",
        "xmlns":"http://oval.mitre.org/XMLSchema/oval-definitions-5#linux"})
    state.append ( __createXMLElement ("evr", "0:"+value,
                    {"datatype":"debian_evr_string", 
                     "operation":operation}))
```

and `value` should be checked for an existing epoch value before prepending `0:` in the `evr` element.

**Comment by iainduncani** [comment]
@SofyaTavrovskaya thanks for your help with this issue last year, I noticed that you are based in the Ukraine.  I really hope that you and your loved ones are safe at the moment 🇺🇦

**Comment by SofyaTavrovskaya** [comment]
@iainduncani   I'm alive, but now I'm in Kharkiv and it's not the safest place in Ukraine. We are bombed by Russian aviation every day, and we don't know, when it stops. But it's dangerous to leave Kharkiv too. For now, we have hundreds deaths among civilian people, and I think, it's not the end.

**Comment by iainduncani** [comment]
@SofyaTavrovskaya oh gosh I don't know what to say! It seems so unjust that two people on a GitHub issue can be living such different lives right now and I am so sorry for what you are going through.  The situation that we see in the news of Kharkiv in particular looks truly awful and although they just feel like insufficient words I really do hope that peace comes to your country soon and you can rebuild your lives.

**Comment by crozzy** [comment]
@SofyaTavrovskaya I am so sorry for what you must be going through, is there some way we can help (justgiving etc.)? Email me in private if needed: jcroslan@redhat.com, joseph.crosland@gmail.com :ukraine:

**Comment by SofyaTavrovskaya** [comment]
@crozzy @iainduncani Thanks for your support. I left Kharkiv two days ago, and now I am in Dnipro, where more calm situation.

**Comment by crozzy** [comment]
It appears that the fix to the debian oval feed generation was merged and I can confirm that we're seeing vulnerabilities described above for this package:

```    "5111201": {
      "id": "5111201",
      "updater": "debian-stretch-updater",
      "name": "CVE-2019-6111 openssh",
      "description": "security update",
      "issued": "0001-01-01T00:00:00Z",
      "links": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-6111",
      "severity": "",
      "normalized_severity": "Unknown",
      "package": {
        "id": "",
        "name": "openssh-client",
        "version": "",
        "kind": "binary",
        "normalized_version": "",
        "cpe": ""
      },
      "distribution": {
        "id": "",
        "did": "debian",
        "name": "Debian GNU/Linux",
        "version": "9 (stretch)",
        "version_code_name": "stretch",
        "version_id": "9",
        "arch": "",
        "cpe": "",
        "pretty_name": "Debian GNU/Linux 9 (stretch)"
      },
      "repository": {
        "cpe": ""
      },
      "fixed_in_version": "1:7.4p1-10+deb9u5"
    },
```

**Comment by crozzy** [comment]
I'm going to close this as the original issue is solved, if there are further data issues with debian feel free to open a new ticket

**Comment by uchi-mata** [comment]
Hi all,
sorry to comment on this closed issue, but I wanted to verify my understanding before filing a new bug.
We are still seeing a lot of occurrences of `0:0` in our images on quay.io ([Example](https://quay.io/repository/astronomer/ap-airflow/manifest/sha256:21708c4c133b1cef82e2cb5b827cf212622c4cb5ef222c4c2084a75a0ee2eebc?tab=vulnerabilities)). Some of them are old findings (i.e. from before the fix was applied), but some seem to be more recent, e.g. for CVE-2022-32207. Fix seems to be available and is listed correctly: https://security-tracker.debian.org/tracker/DSA-5197-1

Would this qualify as a new bug or is this still a long term side effect of this one?

Thanks,
Matthias

**Comment by crozzy** [comment]
Hi @uchi-mata, this seems like a different bug, I wrote up a description here: https://github.com/quay/claircore/issues/673, as you can see in the quay.io link that you added, Clair appears to be reporting both the unpatched and patched advisories.

**Comment by uchi-mata** [comment]
Thank you @crozzy!
