### ISSUE TITLE
detect multiply namespaces in a layer

### ISSUE THREAD

**Issue by liangchenye** [quay/clair#150]
I met this issue when I work on https://github.com/coreos/clair/issues/40.

The current concept of 'namespace' is inherited from 'operating system', so the `debian/redhat/ubuntu` data source which will never coexist with each other in a layer. But if we count npm/python in, we will have multiple namespaces in a layer. 
 I think we need to modify currently scanning process a bit like this:
1. detect multiple namespaces
     `namespace.go:DetectNamespace()` should return a list of `database.Namespace`
2. detect multiple data if we find multiple namespaces
3. scan the layer by multiple namespace database
   layer struct { `Namespace     *Namespace` } should be a list of `database.Namespace`

We can explain 'namespace' in this way: a self-consistent package system. Although `Namespace - a context around features and vulnerabilities` is a better explanation.

**Comment by Quentin-M** [comment]
Well, we anticipated this issue - which is I believe a big leap we need to solve.

For the records, the reason we detect and store namespaces for each layer is because we might not find this information in a particular layer - but only in a previous layer. For example, a layer that simply does `apt-get install` won't modify the files that tell us that this command actually installs `debian:8` packages - and thus, we won't be able to detect it at that point.

If we allow detecting multiple namespaces, then we'll have to pass them to the feature detectors and let them decide which namespace to use for their packages. For instance, if we pass `{"debian:8", "python:2.7"}` to the `dpkg` detector, it should make the decision to use `debian:8` to tag the detected features. This is kind of related to this comment: [51e4086/worker/worker.go#L168](https://github.com/coreos/clair/blob/51e4086/worker/worker.go#L168). We might want to make the `Namespace` structure better. At least, we should make the name and the version two separates fields. In another discussion, I thought about having a third field, which would be filled by the vulnerability fetchers, telling if there's any vulnerability information for that namespace, and maybe a fourth field describing how we could fix/upgrade the features that belongs to that namespace.

Overall, I think this makes sense and the change has to happen one way or another. We just want to make sure that we do it properly, in a way that will give us the most flexibility and extensibility.

**Comment by liangchenye** [comment]
```
NAMESPACE                                    
   |___ TO BE EXTENDED 
   |___ package system
                 |___  rpm
                 |           |___ centos
                 |           |___ redhat 
                 |                        |_____ 5
                 |                        |_____ 6
                 |                        |_____ 7
                 |___  dpkg
                 |           |___ debian
                 |            |___ ubuntu
                 |                       |___ 14.04 
                 |                       | ....
                 |___  npm
```

A feature detector (rpm/dpkg) will support multiple `namespaces` (debian:6/ubuntu:14.04),
I add a new field 'Format' to the Namespace struct. Currently, we only have two formats: dpkg and rpm. The progress so far is good, but the pgsql operation is not finish yet.
https://github.com/liangchenye/clair/tree/multiple-detector

**Comment by jzelinskie** [comment]
Is there any advantage to having a hierarchy like you've shown?

**Comment by liangchenye** [comment]
@jzelinskie  I just want to explain why adding a new field 'Format' to Namespace and why it is sufficient.

**Comment by Quentin-M** [comment]
I see you want to add a `Format` field to `Namespace` but it looks like it may introduce some limitations and I don't really see the value of such field.

I think what we want is:
- Let `Layer` have multiple namespaces, detected by `NamespacesDetector`
- Make `FeaturesDetector` takes a list of namespaces and let each individual detector decide which `Namespace` they want to assign to their detected features. That could be one of the list - or not.

The decision can simply be made based on the name of the `Namespace` I believe.

**Comment by liangchenye** [comment]
Thanks, most codes were done. Still debugging on the sql operation.
