### ISSUE TITLE
Using clair on a private IP

### ISSUE THREAD

**Issue by ghost** [quay/clair#162]
I have set up clair on an AWS VM and I can use it to analyze local images using the contrib tool. I run into issues when I try to use it from my dev machine i.e. laptop which obviously doesnt have public IP. I think this happens since analyze-local-images tool start a HTTP server on local machine but the AWS VM which host clair can't see this IP at all.
1. How should I solve this? I am willing to re-write analyze-local-images code if this can be done keeping current design in mind. 
2. Why clair needs to pull images ? Wont it work if analyze-local images pushes the tarballs instead? Push would be cleaner and more secure right?
3. Support for HTTPS, is it possible to use HTTPS for communication between clair client and clair server?

Any inputs will be appreciated.

**Comment by Quentin-M** [comment]
Hi,

This happens because `analyze-local-images` is intended to let you analyze your _local_ Docker images, to let you discover Clair.
1. You should consider creating a tool for your use-case that would use the [API](https://github.com/coreos/clair/tree/68250f3/api/v1) or using [Hyperclair]https://github.com/wemanity-belgium/hyperclair) if it fits.
2. Correct. This is somewhat related to #112. Pushing layers could be useful and simplify security.
3. Sure. There're two PKI configuration block in [config.example.yaml](https://github.com/coreos/clair/blob/68250f3/config.example.yaml#L42). The first one makes Clair listens over HTTPS (if keyfile/certfile are specified) and optionally verify TLS Client Certs (if a CA is specified). The second one enables the HTTP Notifier talks to an HTTPS endpoint (a CA can be specified to verify the remote public key), and optionally submit TLS Client Certs (keyfile/certfile).

**Comment by ghost** [comment]
Hyperclair or custom tool which I write will still have to open a port and let clair pull tarballs, right? If this is the case then I will hold on till #112 is fixed. Writing a custom tool atop POST would make more sense.

About TLS, this is great. Good to know that communication between analyze-local-images running on host 1 and clair running on host 2 can be encrypted.

**Comment by jgsqware** [comment]
Hyperclair use also a local server and need to allow connection from clair to hyperclair host.

another way is to deploy a registry on your AWS instance and push your image there. Then, you can use hyperclair to analyse those images
