### ISSUE TITLE
Map Source Packages => Binary Packages

### ISSUE THREAD

**Issue by Quentin-M** [quay/clair#185]
In some cases, the Feature names we need to extract to match vulnerabilities isn't the most meaningful for end-users. For instance, when `libssl-dev` is installed, we currently stores `openssl` (the source name), that's how we are able to match its vulnerabilities. However, when it comes to fix the potential issues, reading `libssl-dev` is much more valuable. Thus, it would be nice to have a new field to store that.

The way I see it, we can either add the field to `FeatureVersion` or to `Layer_diff_FeatureVersion`. We can't add it to `Feature` directly because during vulnerability updates, these names are unknown.

**Comment by jzelinskie** [comment]
I've renamed this issue.

We need to document this, too. It's pretty unintuitive that Clair operates on **source packages** which may not correlate one-to-one with the packages users interact with via package managers.

**Comment by KeyboardNerd** [comment]
To make it clear, Clair doesn't operate solely on *source packages*. For example, *rpm* extension extracts the installed binary package name as the feature name. This is due to the fact that OVAL provides vulnerabilities on binary packages. https://github.com/coreos/clair/blob/master/ext/featurefmt/rpm/rpm.go#L64 

In Clair V2, Clair feature does not represent accurate package information because the purpose is to be associated with the vulnerabilities. Therefore, using feature name as package name is actually misleading to the users.

In Clair V3, in our road map, the API response for getting Ancestry ( Image ) vulnerabilities will actually return the installed package names, which is the goal of this issue.

**Comment by KeyboardNerd** [comment]
part 1 differentiate the feature types: #672

**Comment by ldelossa** [comment]
@KeyboardNerd I'm starting to work on this issue. 

As I see it the desire here is to link a CVE with source information to a Binary package. In order to do this during feature detection we need to parse the source package associated with a binary package. I see that RPM is already doing this in the code. Do I have that correct ?

**Comment by KeyboardNerd** [comment]
This source package / binary package information is useful because some vulnerability sources provide vulnerabilities on "source packages" (dpkg) and others on "binary packages" (RPM if I remember correctly).
It's still unclear to us if marking a binary package with the vulnerabilities on source package is a good idea since I don't quite know about how does vulnerabilities are announced.

**Comment by ldelossa** [comment]
Closing this as it's handled in ClairV4.
