### ISSUE TITLE
Add fuzzy support for Alpine based containers

### ISSUE THREAD

**Issue by philips** [quay/clair#187]
Issue #12 is about adding full support for Alpine based images. This would require Alpine to add CVE metadata to their package management.

Instead, as a stop gap we can do "fuzzy support" of Alpine by looking through the `apk` database and fuzzy regex match it to the known CVE database. Explicitly this may create false positives:
- Backports won't be matched (does alpine do backports?)
- Releases with features compiled out will false positive
- Fuzzy matching may break on version things that are hard to compare (non-semvers, etc) 

By doing this we will lose actionable data about how to upgrade the image which is a downside. But, it is better than no data at all.

**Comment by Quentin-M** [comment]
I feel that @eedevops should be added to the conversation.

**Comment by rqc** [comment]
Hello! We are actually working towards adding Alpine support for Clair. We already have a fetcher module and a detector module, both a  WIP: https://github.com/eedevops/clair/tree/eedevops/feature/alpine_support

It would be great to get your feedback asap, but we will eventually submit a pull request to you for review.

The major difference in our approach, is that we de-coupled the _collection_ and _matching_ of the CVEs from the fetcher module. In this way, we are just fetching the reduced list of packages and its CVEs by a simple `http.Get` to a json file in our github repo. Thus, the collector fetches the CVE data from the government website, fetches the known list of packages from the alpine packages website and creates a subset list. Now, this is still a WIP, we would love to add more reliability to the data, by cross-referencing it with the alpine issues website to gather more metadata. If you would like to take a look, you may access the project here: https://github.com/eedevops/alpine_issue_collector 

Thanks!

**Comment by Quentin-M** [comment]
Hi,

We are pretty excited, that is a feature that we desire since the very beginning. Thanks for your work!

I would say that, generally speaking, our main concerns are:
- **accuracy**: vulnerabilities should be up-to-date, as specific and documented as possible,
- **integrity**: it shouldn't be possible to any non-trusted person to alter the data (malicious behavior, non-informed behavior).

How data is generated and where it stays matters less (especially for Alpine!), as long as the points above stand. In fact, the Ubuntu vulnerabilities come from a [bzr repository](https://launchpad.net/ubuntu-cve-tracker). Actually, there is a discussion with Google about maintaining a consolidated and global vulnerability database that every Clair instance could use instead of having to pull various online databases.

Also, could you follow-up on the Alpine mailing-list's thread (http://lists.alpinelinux.org/alpine-devel/5233.html) about them adopting better practice around their existing vulnerability database?

**Comment by rqc** [comment]
@Quentin-M We are excited to be able to contribute back to Clair, since it has been very useful to us. 

As far as the points that you raise above, those are concerns that we also have and we are doing our best to incorporate that into our design. 
- To ensure **integrity** we are hosting the list of vulnerabilities that we have collected and matched in this github repo that is open source. We have control over this repo, so we can make sure that data is uploaded by a trusted collector (we have our own ssh key to ensure this). We are also looking into uploading to an s3 bucket that we also control.
- To ensure **accuracy** we have relied on the government [NVD](https://nvd.nist.gov/) as you have for the other fetchers. Then we cross-reference with [Alpine's own package repository](https://pkgs.alpinelinux.org/packages). However, we are _still missing_ an extra step to cross-reference the reduced CVE list with the [alpine (security) issues](http://bit.ly/28In94k). We think this last step will give it more accuracy and of course we will be able to grab more metadata about the status of those CVEs in Alpine. The issue that we have with that data source is that it is error prone since it is entered by hand, and as it was shown from your discussion with Alpine http://lists.alpinelinux.org/alpine-devel/5233.html they believe that adding more automation or tags to this repo will cause them more overhead. 

It would be great to have Alpine's blessing and cooperation on this. Having Google host a CVE db would also be great. I will definitely engage the Alpine community about their practices and perhaps suggest to them to become design partners with us in the collector / matcher to ensure accuracy and trust. 

Thanks for your feedback!

**Comment by Quentin-M** [comment]
Thanks for the explanation.

For the vulnerability fetchers that Clair currently supports, I intentionally avoided to use the NVD database directly and instead, decided to use distribution-specific databases as they are far more accurate (knowledge about which source code is used / not used, backports, etc). Later, we agreed on [using NVD](https://github.com/coreos/clair/tree/34f62ef/updater/metadata_fetchers/nvd) to populate additional data to known vulnerabilities.

However, I believe that your approach (starting from NVD, creating a subset using Alpine's package repository, adding extra data from Alpine's issues) is totally fair in the current context. We'll be really glad to merge this - and work from there!

**Comment by rqc** [comment]
Hello, we are renewing our efforts to contribute our work back to Clair. We need to make some changes to cleanup and make sure that we are following your contribution guidelines. Let us know if you have any questions or remarks. Thanks!

**Comment by noahwhite** [comment]
That's great news and would be a big contribution to the community.

**Comment by Quentin-M** [comment]
Absolutely, it is the Top1 needed feature and we are really looking forward to it!

**Comment by mattmoor** [comment]
Have you guys considered using: http://git.alpinelinux.org/cgit/alpine-secdb/ ?

You can fetch a .tar.bz of the repo at HEAD via:
   http://git.alpinelinux.org/cgit/alpine-secdb/snapshot/alpine-secdb-master.tar.bz2

**Comment by jzelinskie** [comment]
Nice find @mattmoor! This looks like a good starting place, even though it doesn't look like it's being updated regularly; the last commit was 4 weeks ago.

**Comment by jzelinskie** [comment]
I think this can safely be closed now.
