### ISSUE TITLE
analyze-local-images 500 error

### ISSUE THREAD

**Issue by pennacook** [quay/clair#255]
have clair and postgres installed locally (not containerized). 

receiving:
Could not analyze layer: Got response 500 with message {"Error":{"Message":"database: an error occured when querying the backend"}}

I have verified postgres has data in it.

**Comment by Quentin-M** [comment]
Hi,

Could you check Clair's logs? All database errors are systematically printed there. PostgreSQL logs may contain some information too.

**Comment by pennacook** [comment]
where would Clair log? Not seeing it dump anywhere. I checked PostgreSQL logs and nothing.

**Comment by Quentin-M** [comment]
Clair logs to standard outputs. When containerized, you can simply look at
the container’s logs.

From: Todd W. notifications@github.com notifications@github.com
Reply: coreos/clair
reply@reply.github.com
reply@reply.github.com
Date: October 19, 2016 at 3:00:23 PM
To: coreos/clair clair@noreply.github.com clair@noreply.github.com
Cc: Quentin Machu quentin.machu@coreos.com quentin.machu@coreos.com,
Comment comment@noreply.github.com comment@noreply.github.com
Subject:  Re: [coreos/clair] analyze-local-images 500 error (#255)

where would Clair log? Not seeing it dump anywhere. I checked PostgreSQL
logs and nothing.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
https://github.com/coreos/clair/issues/255#issuecomment-254805162, or mute
the thread

**Comment by pennacook** [comment]
2016-10-19 11:42:04.421335 E | pgsql: searchVulnerabilityFixedInFeature.Scan(): sql: Scan error on column index 2: could not scan a Version from a non-string input

**Comment by jzelinskie** [comment]
closing due to age. this tool is also unsupported.
