### ISSUE TITLE
Clair + Quay question

### ISSUE THREAD

**Issue by arasheedu** [quay/clair#258]
I am getting the below error:

level=fatal msg="Error publishing key" activeKey=<nil> error="Unexpected response code when publishing key: 400 " pendingKey=6WtQzKnVST

Below are the relevant config sections:

jwtproxy:
  signer_proxy:
    enabled: true
    listen_addr: :6063
    ca_key_file: /certificates/mitm.key
    ca_crt_file: /certificates/mitm.crt
    signer:
      issuer: security_scanner
      expiration_time: 5m
      max_skew: 1m
      nonce_length: 32
      private_key:
        type: autogenerated
        options:
          rotate_every: 12h
          key_folder: /config/
          key_server:
            type: keyregistry
            options:
              registry: http://10.0.8.7/keys/

  verifier_proxies:
  - enabled: true
    listen_addr: :6060
    verifier:
      audience: http://10.0.8.6:6060
      upstream: http://localhost:6062
      key_server:
        type: keyregistry
        options:
          registry: http://10.0.8.7/keys/

Any ideas on what's going wrong?

I am using:
quay.io/coreos/quay   v2.0.0
quay.io/coreos/clair-jwt                  v1.2.4

Thanks,
Rasheed

**Comment by Quentin-M** [comment]
Hi,

The key registry returns `400 Bad Request`, I'd start by looking at its logs. The registry URL might be invalid. However, this issue would belong to https://github.com/coreos/jwtproxy rather than Clair but, because in your case, the issue is related to the key registry and it seems to me that you are setting up Clair for Quay Enterprise, I would contact _support@quay.io_ instead.

Thanks.
