### ISSUE TITLE
Question: Can't scan layer from coreos/clair:v1.2.6 image

### ISSUE THREAD

**Issue by oddcb** [quay/clair#268]
Hi. I'm trying to incorporate Clair to scan our images during CI builds.

I've create an image bases off coreos/clair:v1.2.6

The report found here: https://quay.io/repository/coreos/clair/image/7f04c1380cd41970c284252c53eef59f202de69acb61415dde2cb9c67433a4f2?tab=vulnerabilities

lists 127 vulnerabilites. 

When scanning all of the layers in my clair-derived image I only get reported the ones from the file add for file:41ea5187c50116884c38d9 (debian-jessie I guess?). 

So then I just try scanning this layer, and it reports same vulns as quay scan. 
When I submit the layer containg the wget-install it fails, saying: 

```
{
  "Error": {
    "Message": "worker: OS and/or package manager are not supported"
  }
}
```

and in the clair log:

```
clair_clair | 2016-11-12 01:19:21.106470 W | worker: layer sha256:75ea8418708338e40dce9179cfe97fd116831f1601be50fef48ea6011653c986: Layer's namespace is unknown but non-namespaced features have been detected
```

My docker image is simply: 

```
FROM quay.io/coreos/clair:v1.2.6
COPY filer/config.yaml /etc/clair/config.yaml
```

Am I doing anything wrong here, or making any wrong assumptions?

My requests: 

base layer with the file add
```
{
  "Layer": {
    "Name": "sha256:386a066cd84a33a04d560c42bef66d1dd64ebfc76de78550e5fd0f8d57778bca",
    "Path": "https://our-private-repo.org:5000/v2/-/blobs/sha256:386a066cd84a33a04d560c42bef66d1dd64ebfc76de78550e5fd0f8d57778bca",
    "Format": "Docker"
  }
}
```

apt-get install wget layer
```
{
  "Layer": {
    "Name": "sha256:75ea8418708338e40dce9179cfe97fd116831f1601be50fef48ea6011653c986",
    "Path": "https://our-private-repo.org:5000/v2/-/blobs/sha256:75ea8418708338e40dce9179cfe97fd116831f1601be50fef48ea6011653c986",
    "Format": "Docker"
  }
}
```

First lines of get v1/layers/sha256:386a066cd84a33a04d560c42bef66d1dd64ebfc76de78550e5fd0f8d57778bca:

```
{
  "Layer": {
    "Name": "sha256:386a066cd84a33a04d560c42bef66d1dd64ebfc76de78550e5fd0f8d57778bca",
    "NamespaceName": "debian:8",
    "IndexedByVersion": 2,
```

**Comment by Quentin-M** [comment]
Hi,

The reason for your issue is due to the need that Clair has to recognize the underlying namespace (i.e. operating system) and to the nature of layers. The second layer (`apt-get install wget`) simply adds a new package to the system, therefore the filesystem diff of the layer doesn't contain any information about the operating system but only of the added wget feature. Only the first layer contains the fact that the image is based on Debian Jessie. Therefore, when analyzing the second layer, you have to specify in the API parameters that the first layer is its parent. It will enable Clair to understand that the base image of the second layer is Debian Jessie, thus that newly installed `wget` package uses the Debian Jessie's sources, and that every packages/vulnerabilities present in the first layer are carried by the second one too (except of course if something got removed / updated). I hope this makes sense to you. We understand that this can be a bit troubling and there is an open [discussion](https://github.com/coreos/clair/issues/112) on how we could potentially improve the API to allow end-users to pass entire images to Clair.

Instead of using the following JSON payload to analyze the second layer:

```
{
  "Layer": {
    "Name": "sha256:75ea8418708338e40dce9179cfe97fd116831f1601be50fef48ea6011653c986",
    "Path": "https://our-private-repo.org:5000/v2/-/blobs/sha256:75ea8418708338e40dce9179cfe97fd116831f1601be50fef48ea6011653c986",
    "Format": "Docker"
  }
}
```

You must provide the following one:

```
{
  "Layer": {
    "Name": "sha256:75ea8418708338e40dce9179cfe97fd116831f1601be50fef48ea6011653c986",
    "Path": "https://our-private-repo.org:5000/v2/-/blobs/sha256:75ea8418708338e40dce9179cfe97fd116831f1601be50fef48ea6011653c986",
    "Format": "Docker",
    "ParentName": "sha256:386a066cd84a33a04d560c42bef66d1dd64ebfc76de78550e5fd0f8d57778bca",
  }
}
```

One last note, be cautious when solely using a digest for the image name. If the hash is only based on the filesystem change set of the image, it is not unique (i.e. empty filesystem diff on `ENV` layers) and will confuse Clair as it will not be able to maintain correct layer trees.

**Comment by oddcb** [comment]
Thanks! In my code I did submit the ParentName (not the requests I gave here) so I must have managed to get it wrong somehow. 

As I understand it the parent name should be the previous layer and so on?

E.g. top layer = A
And then we have layer b, c

a.parent = null
b.parent = a
c.parent = b

Is that correct? Perhaps that is something that could be clarified in the api docs.

**Comment by Quentin-M** [comment]
Absolutely, you got it right! I agree that the API docs are quite blunt.

**Comment by oddcb** [comment]
Thanks for your assistance @Quentin-M. :-) Another point which also could be put into the documentation is that to get all vulnerabilities one should query the last child layer.
