### ISSUE TITLE
Are bzr and rpm actually needed?

### ISSUE THREAD

**Issue by alexandernst** [quay/clair#291]
Those tools seems to be quite outside of the scope of what Clair does. Are they really needed to build and run Clair?

If "yes", why? And can't those deps be workarounded?

**Comment by Quentin-M** [comment]
Hi,

You can definitely build Clair without `git`, `bzr` and `rpm`. `git` and `bzr` are used to fetch Alpine and Ubuntu vulnerabilities respectively, they enable us to easily perform incremental updates. They may be omitted one way or another. Note that they already use HTTPs for the sake of proxy utilization. `rpm` is required to read the list of packages on CentOS as that data is [stored](https://docs.fedoraproject.org/ro/Fedora_Draft_Documentation/0.1/html/RPM_Guide/RPM_GUide-Using_RPM_DB-working_with_RPM_db.html) in Berkeley DBs.

**Comment by alonrolnik** [comment]
Regarding the `rpm` part, Is it possible to read the list of packages without using `rpm`?

**Comment by KeyboardNerd** [comment]
Since RPM binary is only used for parsing RPM database file `var/lib/rpm/Packages`, it's possible to just use some sort of parser to do it. 
But in practice it's just much more easier to use the RPM binary to give the formatted package information.

If you can find a good go library ( or C lib that can be embedded ) for that purpose, we're happy to use it :)
