### ISSUE TITLE
Possible to integrate Clair with OpenShift Registry?

### ISSUE THREAD

**Issue by mylespollie** [quay/clair#406]
I'm trying to find a way to scan my entire integrated OpenShift Registry.  Does Clair or any of the integrations allow you to scan all the images in a registry at once?

**Comment by jgsqware** [comment]
Clair expose an api. There is no request to scan all your registry. In my
mind, I don't know direct integration with open shift registry.

You have to push all of your images to Clair, you can use tool like
clairctl to help you on that part

**Comment by jzelinskie** [comment]
Is the OpenShift registry open source? It needs to be modified to keep track of images analyzed by Clair and to call the Clair API when one hasn't yet been analyzed.

**Comment by jzelinskie** [comment]
I'm going to close this. This issue should be made on the integration's side of the fence. If there are any actionable items from our side, we can make issues here.

**Comment by caruccio** [comment]
Hey there. You cloud try this clair integration: https://github.com/getupcloud/openshift-clair-controller
It watches for ImageStream updates and scan tags with clair.

**Comment by Chetan8595** [comment]
Hi Caruccio,

I'm trying to integrate Clair with Open-Shift Platform by following the instructions provided in the link: https://github.com/getupcloud/openshift-clair-controller , but i am facing an error:
]$ oc status
In project clair-controller on server https://masterdns36ubif4pta2x4.southindia.cloudapp.azure.com:443

svc/clairsvc (all nodes) ports 6060, 6061
  dc/clair deploys docker.io/getupcloud/clair:latest
    deployment #1 deployed 16 minutes ago - 0/1 pods (warning: 7 restarts)

svc/postgres - 172.30.171.83:5432
  dc/postgres deploys openshift/postgresql:9.5
    deployment #1 failed 16 minutes ago: config change

svc/ruby-ex - 172.30.91.246:8080
  dc/ruby-ex deploys istag/ruby-ex:latest <-
    bc/ruby-ex source builds https://github.com/sclorg/ruby-ex.git on istag/ruby-25-centos7:latest
    deployment #1 deployed 13 minutes ago - 1 pod

dc/clair-controller deploys docker.io/caruccio/claircontroller:latest
  deployment #1 deployed 16 minutes ago - 0/1 pods (warning: 7 restarts)

Errors:
  *** pod/clair-1-2pxl4 is crash-looping
  * pod/clair-controller-1-h92wz is crash-looping**

2 errors, 1 warning, 7 infos identified, use 'oc status --suggest' to see details.

Can i get a suggestion on how to resolve this error and i believe due to this "crash-looping" error, we cannot proceed with the next step,

$ oc label svc/ruby-ex vulnerability.getup.io/clairreport=active
error: 'vulnerability.getup.io/clairreport' already has a value (active), and --overwrite is false

**Comment by caruccio** [comment]
Hey @Chetan8595 could you please move this issue to https://github.com/getupcloud/openshift-clair-controller/issues?
Also, post some error messages from the pod in crashloop and the namespace events:
`oc -n clair-controller  logs -f clair-1-2pxl4`
`oc -n clair-controller get ev`
