### ISSUE TITLE
clair for Singularity images

### ISSUE THREAD

**Issue by vsoch** [quay/clair#434]
hey coreos team! I wanted to extend clair to do checks for Singularity images, and I think I have a good start but wanted to get your feedback on some things. The original issue for Singularity [is here](https://github.com/singularityware/singularity/issues/818). Specifically, we have a time during bootstrap (building an image from docker layers, or from a host mirror) when we run container "checks" and @remed1 wanted to add coreos. I was able to get most of the installation working (it's in a branch I haven't pushed yet, but I [replicated the code here](https://github.com/vsoch/singularity-clair) and now is when I am going to ask some silly questions!

## Is the main user interface the API?
I seem to have set it up ok to be running a server that, when I post requests to it, does respond. It's also doing some kind of updating thing which is taking a long time:

```
{"Event":"Handled HTTP request","Level":"info","Location":"router.go:58","Time":"2017-07-23 17:24:29.185053","elapsed time":1267327,"method":"POST","remote addr":"127.0.0.1:42724","request uri":"/v1/layers","status":"400"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:242","Time":"2017-07-23 17:32:51.872465","updater name":"ubuntu"}
{"Event":"finished fetching","Level":"info","Location":"updater.go:242","Time":"2017-07-23 17:45:45.431658","updater name":"rhel"}
{"Event":"adding metadata to vulnerabilities","Level":"info","Location":"updater.go:268","Time":"2017-07-23 17:45:45.443454"}
```

Based on looking at your API docs, it looks like the expected thing is to post with a layer (with a web accessible address) to perform some kind of check? Is there an ability to use the clair executable from the command line on a file, or even better, for an entire operating system? When we are running this during checks, we will be inside the image being built, so ideally we could just run it over the base root of the image. If that isn't possible, we minimally could add the check to look over the docker layers that a user is adding to the image, or some other compressed tarball.

So - probably the summary of this question is if clair is mostly a vulnerability service vs. an on demand (command line) linter.

## Do you have example use cases?
The docs direct me to how to use the API, or a link to the CoreOS website (and I"m lost in the wilderness at some point). If you have some repos / code with example usage (for the answer to my first question) this would be greatly appreciated!

## Integration with Singularity?
My last question is in observing that the primary way that (I think) you expect to deal with containers is via their layers (eg Docker). Singularity can import layers, but a Singularity image is an entire image (no layers!) So my final question is, given that clair is suited for layers, do you see an avenue to add support for Singularity? If the answer is yes, with some guidance I can probably help to develop some. I don't know go, but if there is a general flow that others have followed to add their containers, I could try mimicking it.

Thanks for your help and feedback!

**Comment by jzelinskie** [comment]
Hey there,

I've never heard of singularity before, so you'll have to fill me in on that.

>Is the main user interface the API?

Yup. Clair does only expose an API. There are unofficial CLI tools (e.g. clairctl) for scanning local images, but the primary use case driving Clair's development is its usage on Quay, CoreOS's registry product. [clairctl](https://github.com/jgsqware/clairctl) or [reg](https://github.com/jessfraz/reg) are probably the best examples you can read that are open source.

Essentially the v1 API revolves around posting JSON that describe a particular docker/aci filesystem "layer" tarball. Clair maintains an index of what features are present in what layers and correlates them in at request-time with a vulnerability database that is regularly updated on a configured interval. The API also supports querying "notifications", which are set of changes to the vulnerability databases that affect the indexed images.

The v2 API (currently WIP) is centered around "Ancestries" rather than individual layers, so it sounds like that might integrate better with Singularity as you've described.

>Do you have example use cases?

Most use cases even outside CoreOS are integrations with docker image registries. Clair is by no means limited to that use case, but that's currently the industry driving its development/usage.

**Comment by vsoch** [comment]
Thanks for your helpful pointers with this! I'll keep the look out for the version 2.0 API. I think this might be useful for Singularity, for sure.
