### ISSUE TITLE
How to use notifications api

### ISSUE THREAD

**Issue by tamalsaha** [quay/clair#549]
Thanks a lot for this project. I am trying to understand how to use the [notifications v3 api](https://github.com/coreos/clair/blob/master/Documentation/notifications.md). I am able to receive notifications via webhook. But I don't understand the request/response objects for this api. Here are some questions I have:

- Why does notification api report both old and new vulnerability? Does this mean old and new vulnerabilities for a feature?
- How does the pagination process work in notification api? How does it work with old /new pages?
- What does `IndexedAncestryName` mean?
- Is there any example of how to use this api?

**Comment by jzelinskie** [comment]
The notifications API is designed for other projects that integrate with Clair to notify users when changes occur in Vulnerability databases. For example, Quay uses this API to inform Quay users when a new vulnerability has been found in a layer (in Clair v2) or image (in Clair v3).

* By presenting the new and old vulnerability, clients can diff the two in order to determine what exactly changed in the Vulnerability database.
* When you query the Notification API, you get a token that you can present for the next page. A new next page token is provided on every page until you reach the last page. This token simultaneously pages over the new and old vulnerabilities. Clients are expected to stream process these results as they page through the Notification. After a client has processed all of the results, they can mark the notification as read.
* IndexedAncestryName contains the SHA256 of the image manifest that is affected and an integer that can be used to sort results. The index can act as a checkpoint as the client processes the stream of results from the notification. If you've reached 500, you are guaranteed to never see an image with an index of less than 500.
* Nope, this is the least stable part of the v3 API and we're still working on getting feedback from integrations. It's really important that it scale for large registries like Quay.io.
