### ISSUE TITLE
False negative in alpine:latest

### ISSUE THREAD

**Issue by LorensK** [quay/clair#566]
**Description of Problem**:

I am investigating a problem I have where Anchore detects a vulnerability that Clair does not. Anchore says that the alpine image has an SSL library that is the object of two CVEs, and my research indicates that Anchore seems to be correct, the problem being related to naming differences between Alpine packages and vulnerability database.

I run a scan of alpine:v3.7.

**Expected Outcome**:

Both Clair and Anchore detect the same vulnerabilities, namely that recent CVEs are filed against libressl 2.6.3, corrected in 2.6.5.

**Actual Outcome**:

Anchore detects

```
Vulnerability ID        Package                               Severity        Fix             Vulnerability URL
CVE-2018-0495           libressl2.6-libcrypto-2.6.3-r0        Unknown         2.6.5-r0        http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-0495
CVE-2018-0495           libressl2.6-libssl-2.6.3-r0           Unknown         2.6.5-r0        http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-0495
CVE-2018-0732           libressl2.6-libcrypto-2.6.3-r0        Unknown         2.6.5-r0        http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-0732
CVE-2018-0732           libressl2.6-libssl-2.6.3-r0           Unknown         2.6.5-r0        http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-0732
```

Clair detects nothing.

**Environment**:
- Clair version/image: v2.0.3
- Clair client name/version: Port Authority (but also hand-curling the API and using psql)
- Host OS: Amazon Linux 18.03
- Kernel (e.g. `uname -a`): 4.14.51-60.38.amzn1.x86_64
- Kubernetes version (use `kubectl version`): none
- Helm version (use `helm version`): none
- Network/Firewall setup: N/A

My alpine:3.7 image reports the following features:

```
[
  { "Name": "libressl2.6-libcrypto", "NamespaceName": "alpine:v3.7", "VersionFormat": "dpkg", "Version": "2.6.3-r0", "AddedBy": "57c971b2aacb8cb523ef97c0469cfc35" },
  { "Name": "libressl2.6-libssl", "NamespaceName": "alpine:v3.7", "VersionFormat": "dpkg", "Version": "2.6.3-r0", "AddedBy": "57c971b2aacb8cb523ef97c0469cfc35" }
]
```

This corresponds to the two libressl features I have on Alpine in the database:

```> select * from featureversion join feature on (feature.id = featureversion.feature_id) join namespace on (namespace.id = feature.namespace_id) where namespace.name='alpine:v3.7' and feature.name ilike '%libressl%' ;
 id | feature_id | version  |  id   | namespace_id |         name          | id |    name     | version_format
----+------------+----------+-------+--------------+-----------------------+----+-------------+----------------
  4 |      18285 | 2.6.3-r0 | 18285 |            1 | libressl2.6-libssl    |  1 | alpine:v3.7 | dpkg
 10 |      18290 | 2.6.3-r0 | 18290 |            1 | libressl2.6-libcrypto |  1 | alpine:v3.7 | dpkg
(2 rows)
```

and the vulnerabilities are in the database... but for feature *libressl* and not the package names libressl2.6-libcrypto / libressl2.6-libssl :

```
select
    vulnerability.name as cve,
    feature.name as feature,
    vulnerability_fixedin_feature.version as fixed
  from vulnerability
  join namespace on (vulnerability.namespace_id = namespace.id)
  join vulnerability_fixedin_feature on (vulnerability.id = vulnerability_fixedin_feature.vulnerability_id)
  join feature on (feature.id = vulnerability_fixedin_feature.feature_id)
  where
    namespace.name='alpine:v3.7' and
    (vulnerability.name = 'CVE-2018-0732'
      or vulnerability.name = 'CVE-2018-0495'
      or vulnerability.name = 'CVE-2017-8301')
  order by cve;
      cve      | feature  |  fixed
---------------+----------+----------
 CVE-2017-8301 | libressl | 2.5.3-r1
 CVE-2018-0495 | libressl | 2.6.5-r0
 CVE-2018-0732 | libressl | 2.6.5-r0
(3 rows)
```

This corresponds to the Alpine cve database, naturally:

https://git.alpinelinux.org/cgit/alpine-secdb/tree/v3.7/main.yaml?id=d432dbe19bf17be3caa9a6b80260edf79d3995e4

```
  - pkg:
      name: libressl
      secfixes:
        2.6.5-r0:
          - CVE-2018-0732
          - CVE-2018-0495
        2.5.3-r1:
          - CVE-2017-8301
```

So, the false negative seems to be due to the difference in names. Either Alpine should use the whole package names, and then Clair would detect the problem, or Clair has/should have an automagical way to detect that packages libressl2.6-libcrypto / libressl2.6-libssl are part of plain libressl... like Anchore seems to have done? If Anchore hadn't seen it I would be reporting this to Alpine directly as an error in their database.

**Comment by jzelinskie** [comment]
This sounds like an upstream issue for the AlpineSecDB repository. Can you create an issue there (or email a maintainer) and ask them to fix this or explain if there is a consistent way to resolve package names that Clair can use? Playing whack-a-mole with rewriting package names is not feasible.

**Comment by LorensK** [comment]
Upstreamed at https://bugs.alpinelinux.org/issues/9067

**Comment by LorensK** [comment]
It seems (see https://bugs.alpinelinux.org/issues/9067) that Alpine intentionally does not list CVEs on "subpackages", and that Clair does not identify the subpackages as belonging to the packages that the CVEs are on. Presumably Anchore manages to do this.

**Comment by jzelinskie** [comment]
Yup, is there a consistent way to resolve the subpackages to a package?

**Comment by glb** [comment]
@KeyboardNerd @jzelinskie https://wiki.alpinelinux.org/wiki/Apk_spec and looking for `libressl` in `/lib/apk/db/installed`  seems to indicate that the `o` line will give you the package.

```sh
/lib/apk/db # grep '^[Po]' installed
P:musl
o:musl
P:busybox
o:busybox
P:alpine-baselayout
o:alpine-baselayout
P:alpine-keys
o:alpine-keys
P:libressl2.7-libcrypto
o:libressl
P:libressl2.7-libssl
o:libressl
P:libressl2.7-libtls
o:libressl
P:ssl_client
o:busybox
P:zlib
o:zlib
P:apk-tools
o:apk-tools
P:scanelf
o:pax-utils
P:musl-utils
o:musl
P:libc-utils
o:libc-dev
```

Not sure if this is a good idea but maybe?

```
diff --git a/ext/featurefmt/apk/apk.go b/ext/featurefmt/apk/apk.go
index f0d29d2..9671500 100644
--- a/ext/featurefmt/apk/apk.go
+++ b/ext/featurefmt/apk/apk.go
@@ -67,6 +67,8 @@ func (l lister) ListFeatures(files tarutil.FilesMap) ([]database.Feature, error)
                switch line[:2] {
                case "P:":
                        pkg.Name = line[2:]
+               case "o:":
+                       pkg.Name = line[2:]
                case "V:":
                        version := string(line[2:])
                        err := versionfmt.Valid(dpkg.ParserName, version)
```

or maybe this would be safer? (**UPDATED:** it's "safer" but it's wrong, and gives bad results a noticeable percentage of the time, see [link](https://github.com/coreos/clair/issues/566#issuecomment-435599096))

```
diff --git a/ext/featurefmt/apk/apk.go b/ext/featurefmt/apk/apk.go
index f0d29d2..b8633af 100644
--- a/ext/featurefmt/apk/apk.go
+++ b/ext/featurefmt/apk/apk.go
@@ -18,6 +18,7 @@ package apk
 import (
        "bufio"
        "bytes"
+       "strings"
 
        "github.com/deckarep/golang-set"
        log "github.com/sirupsen/logrus"
@@ -67,6 +68,11 @@ func (l lister) ListFeatures(files tarutil.FilesMap) ([]database.Feature, error)
                switch line[:2] {
                case "P:":
                        pkg.Name = line[2:]
+               case "o:":
+                       origin := line[2:]
+                       if strings.HasPrefix(pkg.Name, origin) {
+                               pkg.Name = origin
+                       }
                case "V:":
                        version := string(line[2:])
                        err := versionfmt.Valid(dpkg.ParserName, version)
```

Thoughts?

**Comment by glb** [comment]
Experimenting...

For `http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz`: the package named in the `o:` line is **not** a prefix of the `P:` line 504 times out of 5680.

For `http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz`: the package named in the `o:` line is **not** a prefix of the `P:` line 325 times out of 3861.

Spot checks show that there's often a version interjected in the `P:` string.

The `o:` line is always present for packages in this data set.

From the [linked issue](https://bugs.alpinelinux.org/issues/9067), the discussion above, and these results, it seems that we should look up vulnerabilities based on the value in the `o:` line even though the `apk` installed (sub-)package may be named slightly differently.

If we use the `o:` line as the package name and there are multiple sub-packages installed, the `ListFeatures` function will just report the name of the main package. The original description of this issue shows that Anchore reports the name of the sub-package.

A few paths seem like possible options:
1. change the Alpine vulnerability feed parser to register vulnerabilities against all known sub-packages. This seems potentially a bit odd as we could end up reporting vulnerabilities for doc packages or we could get duplicates as seen in the Anchore output shown above, but you would get the real package name. I'm not sure that this is possible as it seems we'd need to enumerate and download all of the `APKINDEX` files for all releases to proactively explode the vulnerabilities out to the sub-packages.
2. change the feature lister to use the main package as the detected feature. This reduces duplicate data but people might find it harder to map the packages that they think they've installed to the features that Clair is reporting.
3. implement an alternative field for mapping features to vulnerabilities that Alpine would populate with the main package name, keeping the sub-package name as the feature name. Everything else would leave this alternative field blank and the mapping logic would fall back to current behaviour of using the feature name. I haven't looked at the detail of how vulnerabilities are mapped to features yet, so I don't fully know what would be involved in this or if it would require a database schema change. This would give equivalent behaviour to option 1 without the need to tackle the `APKINDEX` problem.

All of these options risk false positives (as a bad example in the container space `dhcp`, `dhclient`, and `dhcrelay` are sub-packages of the `dhcp` package, so if you install only `dhclient` you might see vulnerabilities for `dhcp`, because the vulnerabilities are listed against the main package). This seems to be an inherent problem with the way the Alpine data is structured.

Are there options I haven't considered? Any suggestions?

**Comment by KeyboardNerd** [comment]
`o:` contains the origin package if it's different from the 'P:' field.
Using this name may introduce false positive because the sub package may not contain that specific vulnerability. 
One problem of using the origin package as feature is that the user will see the origin package instead of the actually installed package in the vulnerability report. 
We're working on updating the database schema to provide a more robust way of storing the packages and their relations as features.

Therefore, In the long run, it requires a database schema update. In the short run, we can just use the 'o:' package as feature to decrease the false-negative and increase false-positive. 
I think there's no perfect way of solving this problem but only best effort.

**Comment by glb** [comment]
@KeyboardNerd agreed that there is no perfect solution as the data is not mapped to the sub-package.

Do you want a PR for the simple change to use the `o:` line that I outlined [above](https://github.com/coreos/clair/issues/566#issuecomment-435544022)?

**Comment by bgoareguer** [comment]
I am having the same problem with Clair missing some CVEs in Alpine images. Is there any update on this?

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
