### ISSUE TITLE
Support application dependencies at Clair

### ISSUE THREAD

**Issue by krishnapaparaju** [quay/clair#588]
**Description of Problem**:
Clair is a great tool for flagging vulnerabilities at system/operating system level dependencies.  Currently Clair does not flag vulnerabilities for application level dependencies (eg: Maven, Python, Node). Along with vulnerabilities, with ever increasing ecosystem around application level dependencies it would be great value add if Clair provide detailed application dependency health check for a container image to cover license compliance, current version used Vs. Latest version, and Insights to suggest additional / alternative dependencies.

**Expected Outcome**:
For a container image, Clair provide these insights for application dependencies:
 

- Vulnerabilities with CVSS score, suggest upgrading to a version to fix the indicated vulnerability

- Flag if currently used version is way behind the current latest version 

- Flag license conflicts if application stack level license can not be determined 

- Suggest any additional application dependencies (AI driven, based on understanding intent of currently used application dependencies)

- Suggest any alternative application dependencies to replace currently used application dependencies (AI driven, based on understanding intent of currently used application dependencies)

**Integration of OpenShift.IO AI platform with Clair**:
OpenShift.IO AI platform power cloud development experience of OpenShift.IO users with complete health check  and AI based insights around application dependencies. Currently Node and Maven are supported.  Roadmap include supporting Python, GO and Ruby languages.

Check out [screenshot](https://drive.google.com/file/d/1xllBZgCyDEMFZWWQWecIcO4sU0NaVVtR/view?usp=sharing) for a detailed application stack report at OpenShift.IO.
 

**Actual Outcome**:
Currently no support is available for any insights around application dependencies.

**Environment**:
NA

**Comment by jzelinskie** [comment]
The big architectural difference between Clair v2 and v3 is that v3 should now be able to support these application level dependencies. The only problem now is that none have been implemented yet. I don't mind creating issues for individual requests (e.g. node, Go). In these threads we can discussion the strategy for detecting the packages and what should be the canonical source of vulnerability data for these types of packages.

License checking is completely separate feature request that we haven't spent any time thinking about. You can create a separate issue tracking that as well, if you'd like.

Your AI ideas are interesting and I think should be prototyped outside of Clair before we experiment with anything in Clair itself.

I'm going to close this issue because it's very generic and we should ideally create more granular issues out of it.

**Comment by sschuberth** [comment]
Hi, I'm sorry to comment on this old issue, but as it talks about "Maven" I'm wondering what source of known vulnerabilities Clair is using for Maven packages, as in the [docs](https://quay.github.io/claircore/) I cannot find a Maven-/ Java-specific provider being mentioned.

Any hints?
