### ISSUE TITLE
[question] clair vuln DB

### ISSUE THREAD

**Issue by choman** [quay/clair#595]
where does one find the vulnerability sql files?

**Comment by MackJM** [comment]
What do you mean? The DB holds all the vulnerabilities, if you could dump the database if you wanted sql files.

**Comment by choman** [comment]
My clair server is on a closed network.  So I was looking for a trusted source to download the sql files

**Comment by KeyboardNerd** [comment]
Offline database loading/scanning feature is not implemented yet. You can probably just run an instance of Clair on public internet environment, dump the database and load it in your offline postgresql database, but it'll be tricky because the join tables requires the indexes to be exact. This way you can get the scanning working but the vuln database won't be able to get updated.

**Comment by choman** [comment]
roger that, I'll check back if I run into issue

**Comment by jzelinskie** [comment]
Duplicate of #401
