### ISSUE TITLE
Clair only analyzes layers' added content

### ISSUE THREAD

**Issue by jzelinskie** [quay/clair#635]
### Description of Problem / Feature Request

Clair checks _added_ files in each layer. Afterwards, a comparison of the lists of packages occurs to determine what was added or removed.

Rather, Clair could analyze both the _added_ and _removed_ files and calculate a diff at that point. This information is immutable and can be reused when analyzing new ancestries with the same layer. 

### Environment

N/A

**Comment by KeyboardNerd** [comment]
The current model of Clair is based on scanning the Package managers to extract the features.
Removing the Package manager database may not indicate that all the features from that package manager is removed.
However, say, a vulnerability could be indicated from the existence of a file in a layer, we can safely say that if a layer removes that specific file, the layer will not have this feature any more. 

Therefore, we need to be really careful about the assumption of what removing a file indicates. 
If we're going to implement this, the assumption should be coded by each detector instead of by the core logic.

I'll work on the database implementation and extend the detector interfaces for this feature, but it will not affect any current scan result.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
