### ISSUE TITLE
Clair doesn't report correctly image health.

### ISSUE THREAD

**Issue by jihed** [quay/clair#710]
### Description of Problem / Feature Request
I am using clair-jwt image version 2.07 with Quay inside openshift.
I pushed an "bad" image (rhel based) which have vulnerability RHSA-2018:3092. When I checked the Quay repo interface: the security status is 'Passed'. 
However in the clairdb, I could see the metadata of this CVE on the vulnerability table

### Expected Outcome

Report the vulnerability about this image

### Actual Outcome

Passed 'green'.

### Environment

- Clair version/image: 2.07
- Clair client name/version: clair-jwt
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): openshift 3.9
- Helm version (use `helm version`): 
- Network/Firewall setup: managed by iptables (kubernetes rules).

**Comment by KeyboardNerd** [comment]
RHEL is not well supported. We're working on it.

There are 3 things to make clair knows an image has the vulnerability.
1. the vulnerability to exist in the db
2. the namespace (rhel) of the vulnerability must match the namespace of the package
3. the vulnerability must have the information indicating that the version the package is fixed in is less than the package version found in your container image.

I guess in your db, (2) is not satisfied.
