### ISSUE TITLE
Unable to scan alpine/edge

### ISSUE THREAD

**Issue by mfmcdonagh** [quay/clair#737]
### Description of Problem / Feature Request

I'm trying to scan alpine:edge (it was updated last friday) and i'm getting the error above, prior to yesterdays update I could scan it.

### Expected Outcome

Clair should be able scan alpine:edge for vulnerabilities

### Actual Outcome

Could not analyze layer: Clair responded with a failure: Got response 422 with message {"Error":{"Message":"worker: OS and/or package manager are not supported"}}

### Environment

- Clair version/image: 2.0.7
- Clair client name/version: clair-scanner
- Host OS:  Ubuntu
- Kernel (e.g. `uname -a`): 4.4.0-141-generic
- Kubernetes version (use `kubectl version`):  N/A
- Helm version (use `helm version`):  N/A
- Network/Firewall setup: N/A

**Comment by KeyboardNerd** [comment]
Since this is not an official release, there's no vulnerability data source for this release in [here](https://github.com/alpinelinux/alpine-secdb). Clair will not be able to support this namespace.

The direct reason is that:
https://github.com/coreos/clair/blob/master/ext/featurens/alpinerelease/alpinerelease.go#L50
and in `alpine:edge` `/etc/alpinerelease` file contains version:
```
3.10_alpha20190228
```
which does not match the regex.
