### ISSUE TITLE
Alpine secdb is inadequate as a vulnerability source

### ISSUE THREAD

**Issue by KeyboardNerd** [quay/clair#754]
### Description of Problem / Feature Request
In this repo: https://github.com/alpinelinux/alpine-secdb
It clearly says in README.md:
```
The purpose of this database is to make it possible to know what packages has
backported fixes. It is not a complete database of all security issues in
Alpine, and it should be used in combination with another more complete CVE
database.
```
It only contains all the backports but *not* what is currently being affected!

### Environment

- Clair version/image: master
- Clair client name/version: 
- Host OS: 
- Kernel (e.g. `uname -a`): 
- Kubernetes version (use `kubectl version`): 
- Helm version (use `helm version`): 
- Network/Firewall setup:

**Comment by julianseeger** [comment]
Is there a reason why this is not `priority/high` and `kind/bug`?
As the Alpine secdb is actually a whitelist of backported fixes and not at all a list of vulnerabilities, relying solely on secdb to actually find vulnerabilities is absolutely insecure (makes no sense at all). And as alpine is pretty popular in container images, this issue makes clair very unreliable of not kind of useless.

**Comment by jzelinskie** [comment]
I've labeled this as external and friction. I'm not sure the best label for prioritization because I do not think there is a clear path forward for fixing this problem.

The Alpine Sec-DB claims that it needs to be used in conjunction with another CVE database.
While this is a noble acknowledgement, Alpine Linux makes no effort to map versions of their packages with some consistent identifier for the version of the software. For example, NVD uses the [CPE format] to refer to vulnerable software versions. For most security products, this data is produced by humans and kept proprietary as a competitive advantage. Alpine Linux isn't unique to this problem; the Debian project has had a proposal for 10 years about including CPE metadata in a database for their packages. FWIW, KubeDex actually has a pretty good summary about this in their [Container Scanning Comparison].

A potential band-aid could be to assume that the `$BACKPORT_VERSION-1` is vulnerable. This isn't guaranteed to be true, though. In its current form, Clair isn't currently providing false negatives and people just need to upgrade to `$BACKPORT_VERSION+1` to pass the scan.

Clair can only be as good as the publicly available resources. Given a budget, someone could afford to fund a database that could rival the proprietary ones and make it available for everyone. That sounds like the role of a non-for-profit foundation, though.

[CPE format]: https://nvd.nist.gov/products/cpe
[Container Scanning Comparison]: https://kubedex.com/follow-up-container-scanning-comparison/

**Comment by julianseeger** [comment]
> Clair isn't currently providing false negatives

that might be correct "currently" but it just 4 days ago, there were multiple false negatives in [clamav](https://github.com/alpinelinux/alpine-secdb/commit/1835094d59c9297ba4c9d4615a86f7c7a828f172#diff-80435468777cd621de77bf45c25d505f). The problem with the `$BACKPORT_VERSION-1` is that until fixed, CVEs don't show up in the secdb at all. That makes all unfixed CVEs false negatives regarding the secdb.

> Alpine Linux makes no effort to map versions of their packages with some consistent identifier

Sure, I see the point, so there won't be any complete solution.
I'm wondering if one could at least shorten the gap for those false negatives. In the example of clamav, the NVD-Feed showed these Informations:
```json
      "affects" : {
        "vendor" : {
          "vendor_data" : [ {
            "vendor_name" : "clamav",
            "product" : {
              "product_data" : [ {
                "product_name" : "clamav",
                "version" : {
                  "version_data" : [ {
                    "version_value" : "0.101.1",
                    "version_affected" : "<="
                  } ]
```
```json
    "configurations" : {
      "CVE_data_version" : "4.0",
      "nodes" : [ {
        "operator" : "OR",
        "cpe_match" : [ {
          "vulnerable" : true,
          "cpe23Uri" : "cpe:2.3:a:clamav:clamav:*:*:*:*:*:*:*:*",
          "versionEndIncluding" : "0.101.1"
        } ]
      } ]
    }
```

While it's obviously a workaround, one could try to find CPEs by assuming vendor=package_name and product_name=package_name. That wouldn't find all packages of course but at least a couple of them, probably leading to fewer falses (fewer negatives and hopefully no positives).

Alternatively: would it be a viable approach to have a mapping in clair for alpine-package<->CPE? That mapping would mostly be an add-only list and even if it starts with just a handful of packages, it would immediately provide fewer false negatives with no reason for false positives. And mapping those 185 Packages covered by the secdb should be doable ...it just sounds wasteful to ignore the NVD-Feed if it's already integrated in clair.

**Comment by jzelinskie** [comment]
>Alternatively: would it be a viable approach to have a mapping in clair for alpine-package<->CPE? That mapping would mostly be an add-only list and even if it starts with just a handful of packages, it would immediately provide fewer false negatives with no reason for false positives. And mapping those 185 Packages covered by the secdb should be doable ...it just sounds wasteful to ignore the NVD-Feed if it's already integrated in clair.

Our philosophy has been to try and stick with the vulnerability data that is maintained closest to the artifacts themselves in order to avoid invalid data. Cross-referencing will vastly complicate maintaining that validity and make it very difficult to inform users of _why_ we think something is vulnerable. It might seem wasteful to ingest metadata like NVD, but not use it, but we do not have knowledge on whether or not something has been patched in a particular package if we naively map NVD's reported versions to a different context like Debian or RHEL.

I think diving into the above topic is a great exercise, but one that would should take place somewhere where we're discussing making larger architectural changes to Clair. 

---

Another alternative that [trivvy](https://github.com/knqyf263/trivy) does is to basically attempt to read the data out of Redmine using a basic search query similar to [this](https://bugs.alpinelinux.org/projects/alpine/search?q=CVE&scope=subprojects&titles_only=1&utf8=%E2%9C%93) and speculatively parsing the dynamic, handwritten content. See their written comparison [here](https://github.com/knqyf263/trivy#vs-clair). I haven't looked at the code or data produced to know if they're able to generate accurate results, but "parse git logs" was one of the first things the Alpine maintainers told us to do before they had SecDB.

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
