### ISSUE TITLE
Add support not only tar layouts

### ISSUE THREAD

**Issue by mrqwer88** [quay/clair#8]
Hello!

How I see clair can add layouts only in tar archives now.
Are planned add layouts like directory and tar.gz?
As example with tar.gz support it be more comfortably to check OpenVZ templates - https://download.openvz.org/template/precreated/ ( if ungzip it - clair work correctly with this templates ).
And if clair can work with directory - it can check already created openvz containers and etc.

**Comment by Quentin-M** [comment]
Hello,

Clair is actually able to accept .tar.gz archives already! However, it does not accept directories yet but it would really be a quick feature to add. Using Clair against OpenVZ containers is a pretty good idea. OpenVZ templates can be seen as one layer images. I am myself an user of OpenVZ and I never had that thought before.

However, be aware that Clair has initially been designed to analyze huge amount of images/templates, (which are immutable) and because of that, you can't just re-submit an image with the same ID and expect Clair to analyze it again, it will skip the analysis saying that it already knows about that image. Clair will only analyze images again if it's engine version is increased (meaning that Clair could know learn more about images). It makes it kinda unsuitable for analyzing mutable systems like running containers.

**Comment by mrqwer88** [comment]
Thanks for answers.

Yes, with tar.gz clair work correctly  too - my bad.

Re-submit for containers not a problem - in any case, the addition would be to go through the script.
If be added support for add layouts via directory.

**Comment by mrqwer88** [comment]
And little wrapper for add templates from openvz 6 mirror to clair - [check_openvz_mirror_with_clair](https://github.com/FastVPSEestiOu/check_openvz_mirror_with_clair)

**Comment by Quentin-M** [comment]
That's really cool ! That could totally go to the `contrib/` folder under that repository. Make a pull request when you think your tool is ready/mature enough. I will be glad to merge it.
