### ISSUE TITLE
questions about submitting data

### ISSUE THREAD

**Issue by fxdgear** [quay/clair#810]
Related: https://github.com/coreos/clair/issues/127

Reading through how to implement integrating with Clair I've found that in order to submit data to clair for scanning I have to give clair the URL to download the tarbal'd layer. 

The docs regarding auth etc aren't super well flushed out so I have a couple questions. 

1. Can I just send clair the tar file of the layer in question? 
2. How does auth work? Do i need to get a JWT from my auth server and send it along with the request to clair to download? 
3. Can clair be configured with a username/password to communicate to the registry? As opposed to sending authentication creds on every request

These seem like weird workaround when it would just be easier to give the data to clair instead of telling it how to download the data.

**Comment by dgrahn** [comment]
It would be fantastic if we could run against local images.

**Comment by fxdgear** [comment]
Not stale. Just ignored.

**Comment by jzelinskie** [comment]
>Can I just send clair the tar file of the layer in question?

If it's on the local machine you can use a filepath instead of a URL.

>How does auth work? Do i need to get a JWT from my auth server and send it along with the request to clair to download?

It's left open ended -- Clair allows you to specify the URL and any arbitrary HTTP headers.

> Can clair be configured with a username/password to communicate to the registry? As opposed to sending authentication creds on every request

This seems like a reasonable feature request worth creating an issue for. We hadn't considered it in the past because many registries implement pulling using temporarily signed URLs that expire.

>These seem like weird workaround when it would just be easier to give the data to clair instead of telling it how to download the data.

Clair is originally designed for the large task of indexing a whole registry and thus isn't the most ergonomic for scanning one or two images on your laptop.

For more related to the original title, see #112

**Comment by hdonnay** [comment]
We’re declaring bug bankruptcy as part of the release process for a new major version of Clair. Please open a ticket in our [issue tracker](https://issues.redhat.com/projects/PROJQUAY/) if you feel this still needs to be addressed, and we'll triage as part of our v4 development process. Thanks!
