### ISSUE TITLE
Helm chart?

### ISSUE THREAD

**Issue by bitsofinfo** [quay/clair#928]
Where is the helm chart I can deploy this to a k8s cluster?

**Comment by mluyun** [comment]
I was looking for the helm chart as well.

**Comment by ldelossa** [comment]
Due to the different ways of deploying a service like Clair, we will not be supporting a Helm chart which pins the deployment in one direction.

**Comment by bitsofinfo** [comment]
huh? how does providing a helm chart pin clair into anything?

**Comment by abdennour** [comment]
@ldelossa  Really,  I am still not convinced. Helm has been invented to overcome challenges that you mentioned.
With this great **package manager**, you can cover all cases: k8s environment, OCP 3.x env, OCP 4.x env, ...etc. 

Please , this is another call to support it. Otherwise, [kuberenetes.tn](http://kuberenetes.tn) will support it in [their repository ](https://github.com/kubernetes-tn/charts/tree/master/stable). However, we will be forced to do it if you will not make it available here.


@bitsofinfo  @mluyun  this repository supported before the Helm chart. I found this link somewhere else : 
https://github.com/quay/clair/tree/3617b7a12646d9d5f68ec057ed327b2f16ffeafb/contrib/helm/clair
But i am pretty sure it is outdated.

@bitsofinfo  i am afraid that this tool will be sold by Red Hat as previous tools (OCP, ...): If it's not the tool itself, its dependencies ( helm chart, docs, ...) may be the target of sales . 
Hopefully, I am thinking wrongly.

**Comment by ldelossa** [comment]
ClairV2 and ClairV3 are under community maintenance. Feel free to submit a Helm pr to those release branches. 

ClairV4 will not support Helm in favor of Kustomize.
